In [1]:
#dependencies
from bs4 import BeautifulSoup as bs
import requests
from splinter import Browser
import pandas as pd
import time
from sqlalchemy import create_engine

# Step 1: Extract

### Table 1: Disney movies table
source: kaggle https://www.kaggle.com/prateekmaj21/disney-movies

In [16]:
disney_df = pd.read_csv('Resources/disney_movies.csv')
disney_df.head()

,movie_title,release_date,genre,mpaa_rating,total_gross,inflation_adjusted_gross
0,Snow White and the Seven Dwarfs,1937-12-21,Musical,G,184925485,5228953251
1,Pinocchio,1940-02-09,Adventure,G,84300000,2188229052
2,Fantasia,1940-11-13,Musical,G,83320000,2187090808
3,Song of the South,1946-11-12,Adventure,G,65000000,1078510579
4,Cinderella,1950-02-15,Drama,G,85000000,920608730

### Table 2: 
source: IMDB website https://www.imdb.com/list/ls068561553/

Extract from IMDB to get movie duration, IMDB_rating, Number_of_reviews,

In [2]:
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser("chrome", **executable_path, headless=False)

In [3]:
rating_list = []
title_list = []
duration_list = []
number_of_reviews = []

url = "https://www.imdb.com/list/ls068561553/"
browser.visit(url)


for x in range(1, 7):
    html = browser.html
    soup = bs(html, 'html.parser')
    contents = soup.find_all("div", class_='lister-item-content')

    for content in contents:
        print("----------------------")
        
        #extract movie title and imdb-ratings
        try:
            title = content.find('a').text
            print(f"Movie title: {title}")
            title_list.append(title)

            rating = content.find('span', class_="ipl-rating-star__rating").text
            print(f"Rating: {rating}")
            rating_list.append(rating)            
            
          
        except:
            print(f"Oops, rating not found! ")
            rating_list.append("")
            
        # extract movie durations    
        try:
            duration = content.find('span', class_="runtime").text
            print(f"duration: {duration}")
            duration_list.append(duration)
            
        except:
            print("Oops, duration not found!")
            duration_list.append("")
        
        #extract number of reviews
        try:
            vote = content.find("span" , {"name" : "nv"}).text
            print(f"number_of_reviews: {vote}")
            number_of_reviews.append(vote)
        
        except:
            print(f"Oops, number of reviews not found!")
            number_of_reviews.append("")
            
            
            
    browser.click_link_by_partial_text('Next')
    time.sleep(2)

----------------------
Movie title: Snow White and the Seven Dwarfs
Rating: 7.6
duration: 83 min
number_of_reviews: 173,805
----------------------
Movie title: Pinocchio
Rating: 7.4
duration: 88 min
number_of_reviews: 124,575
----------------------
Movie title: Fantasia
Rating: 7.8
duration: 125 min
number_of_reviews: 85,242
----------------------
Movie title: The Reluctant Dragon
Rating: 6.9
duration: 74 min
number_of_reviews: 2,448
----------------------
Movie title: Dumbo
Rating: 7.2
duration: 64 min
number_of_reviews: 114,587
----------------------
Movie title: Bambi
Rating: 7.3
duration: 70 min
number_of_reviews: 125,811
----------------------
Movie title: Saludos Amigos
Rating: 6.2
duration: 42 min
number_of_reviews: 4,784
----------------------
Movie title: Victory Through Air Power
Rating: 6.6
duration: 70 min
number_of_reviews: 825
----------------------
Movie title: The Three Caballeros
Rating: 6.5
duration: 71 min
number_of_reviews: 11,476
----------------------
Movie title: Make Mine Music
Rating: 6.3
duration: 75 min
number_of_reviews: 3,443
----------------------
Movie title: Song of the South
Rating: 7.1
duration: 94 min
number_of_reviews: 10,684
----------------------
Movie title: Fun and Fancy Free
Rating: 6.6
duration: 73 min
number_of_reviews: 6,468
----------------------
Movie title: So Dear to My Heart
Rating: 6.8
duration: 79 min
number_of_reviews: 1,205
----------------------
Movie title: Melody Time
Rating: 6.4
duration: 75 min
number_of_reviews: 4,489
----------------------
Movie title: The Adventures of Ichabod and Mr. Toad
Rating: 7
duration: 68 min
number_of_reviews: 11,864
----------------------
Movie title: Treasure Island
Rating: 6.9
duration: 96 min
number_of_reviews: 6,603
----------------------
Movie title: Cinderella
Rating: 7.3
duration: 74 min
number_of_reviews: 139,385
----------------------
Movie title: Alice in Wonderland
Rating: 7.4
duration: 75 min
number_of_reviews: 123,371
----------------------
Movie title: The Story of Robin Hood and His Merrie Men
Rating: 6.7
duration: 84 min
number_of_reviews: 1,330
----------------------
Movie title: Peter Pan
Rating: 7.3
duration: 77 min
number_of_reviews: 120,322
----------------------
Movie title: Rob Roy: The Highland Rogue
Rating: 6.3
duration: 81 min
number_of_reviews: 476
----------------------
Movie title: The Sword and the Rose
Rating: 6.5
duration: 92 min
number_of_reviews: 704
----------------------
Movie title: 20,000 Leagues Under the Sea
Rating: 7.2
duration: 127 min
number_of_reviews: 27,806
----------------------
Movie title: Lady and the Tramp
Rating: 7.3
duration: 76 min
number_of_reviews: 116,978
----------------------
Movie title: The Littlest Outlaw
Rating: 6.1
duration: 73 min
number_of_reviews: 190
----------------------
Movie title: Davy Crockett: King of the Wild Frontier
Rating: 7
duration: 93 min
number_of_reviews: 3,374
----------------------
Movie title: Westward Ho, the Wagons!
Rating: 5.8
duration: 90 min
number_of_reviews: 279
----------------------
Movie title: Davy Crockett and the River Pirates
Rating: 6.8
duration: 81 min
number_of_reviews: 1,636
----------------------
Movie title: The Great Locomotive Chase
Rating: 6.9
duration: 85 min
number_of_reviews: 1,003
----------------------
Movie title: Old Yeller
Rating: 7.3
duration: 83 min
number_of_reviews: 11,224
----------------------
Movie title: Johnny Tremain
Rating: 6.5
duration: 80 min
number_of_reviews: 1,522
----------------------
Movie title: Tonka
Rating: 6.5
duration: 97 min
number_of_reviews: 351
----------------------
Movie title: The Light in the Forest
Rating: 6.4
duration: 83 min
number_of_reviews: 489
----------------------
Movie title: The Shaggy Dog
Rating: 6.5
duration: 104 min
number_of_reviews: 4,153
----------------------
Movie title: Sleeping Beauty
Rating: 7.2
duration: 75 min
number_of_reviews: 129,674
----------------------
Movie title: Third Man on the Mountain
Rating: 7.2
duration: 107 min
number_of_reviews: 767
----------------------
Movie title: Darby O'Gill and the Little People
Rating: 7.2
duration: 93 min
number_of_reviews: 6,668
----------------------
Movie title: Swiss Family Robinson
Rating: 7.2
duration: 126 min
number_of_reviews: 13,342
----------------------
Movie title: Ten Who Dared
Rating: 5.7
duration: 92 min
number_of_reviews: 193
----------------------
Movie title: Kidnapped
Rating: 6.6
duration: 97 min
number_of_reviews: 1,235
----------------------
Movie title: Toby Tyler or Ten Weeks with a Circus
Rating: 7
duration: 96 min
number_of_reviews: 823
----------------------
Movie title: Pollyanna
Rating: 7.4
duration: 134 min
number_of_reviews: 8,619
----------------------
Movie title: The Sign of Zorro
Rating: 7.1
duration: 91 min
number_of_reviews: 669
----------------------
Movie title: The Absent Minded Professor
Rating: 6.8
duration: 92 min
number_of_reviews: 6,969
----------------------
Movie title: Greyfriars Bobby: The True Story of a Dog
Rating: 7.3
duration: 87 min
number_of_reviews: 1,203
----------------------
Movie title: The Parent Trap
Rating: 7.1
duration: 129 min
number_of_reviews: 17,989
----------------------
Movie title: Babes in Toyland
Rating: 6.3
duration: 106 min
number_of_reviews: 3,244
----------------------
Movie title: One Hundred and One Dalmatians
Rating: 7.2
duration: 79 min
number_of_reviews: 146,163
----------------------
Movie title: In Search of the Castaways
Rating: 6.6
duration: 98 min
number_of_reviews: 2,674
----------------------
Movie title: The Legend of Lobo
Rating: 7
duration: 67 min
number_of_reviews: 432
----------------------
Movie title: Almost Angels
Rating: 6.7
duration: 93 min
number_of_reviews: 357
----------------------
Movie title: Big Red
Rating: 6.4
duration: 89 min
number_of_reviews: 653
----------------------
Movie title: Moon Pilot
Rating: 5.4
duration: 98 min
number_of_reviews: 355
----------------------
Movie title: Bon Voyage!
Rating: 5.8
duration: 130 min
number_of_reviews: 545
----------------------
Movie title: Miracle of the White Stallions
Rating: 6.6
duration: 93 min
number_of_reviews: 534
----------------------
Movie title: Summer Magic
Rating: 7
duration: 110 min
number_of_reviews: 2,056
----------------------
Movie title: Savage Sam
Rating: 6.3
duration: 103 min
number_of_reviews: 888
----------------------
Movie title: The Incredible Journey
Rating: 7.1
duration: 80 min
number_of_reviews: 3,725
----------------------
Movie title: The Sword in the Stone
Rating: 7.2
duration: 79 min
number_of_reviews: 85,363
----------------------
Movie title: Son of Flubber
Rating: 6.1
duration: 100 min
number_of_reviews: 2,561
----------------------
Movie title: Mary Poppins
Rating: 7.8
duration: 139 min
number_of_reviews: 151,423
----------------------
Movie title: A Tiger Walks
Rating: 6.4
duration: 91 min
number_of_reviews: 260
----------------------
Movie title: The Misadventures of Merlin Jones
Rating: 6.4
duration: 91 min
number_of_reviews: 613
----------------------
Movie title: The Three Lives of Thomasina
Rating: 7.2
duration: 97 min
number_of_reviews: 2,058
----------------------
Movie title: The Moon-Spinners
Rating: 6.7
duration: 118 min
number_of_reviews: 1,998
----------------------
Movie title: Emil and the Detectives
Rating: 6.2
duration: 99 min
number_of_reviews: 444
----------------------
Movie title: That Darn Cat!
Rating: 6.8
duration: 116 min
number_of_reviews: 5,576
----------------------
Movie title: The Monkey's Uncle
Rating: 6.1
duration: 87 min
number_of_reviews: 707
----------------------
Movie title: Those Calloways
Rating: 6.7
duration: 131 min
number_of_reviews: 474
----------------------
Movie title: The Ugly Dachshund
Rating: 6.7
duration: 93 min
number_of_reviews: 3,287
----------------------
Movie title: Follow Me, Boys!
Rating: 7.2
duration: 131 min
number_of_reviews: 2,038
----------------------
Movie title: The Fighting Prince of Donegal
Rating: 6.2
duration: 110 min
number_of_reviews: 320
----------------------
Movie title: Lt. Robin Crusoe, U.S.N.
Rating: 6.1
duration: 110 min
number_of_reviews: 1,183
----------------------
Movie title: The Jungle Book
Rating: 7.6
duration: 78 min
number_of_reviews: 159,308
----------------------
Movie title: The Happiest Millionaire
Rating: 6.9
duration: 141 min
number_of_reviews: 1,705
----------------------
Movie title: Charlie, the Lonesome Cougar
Rating: 6.9
duration: 75 min
number_of_reviews: 759
----------------------
Movie title: The Gnome-Mobile
Rating: 6.6
duration: 84 min
number_of_reviews: 1,891
----------------------
Movie title: The Adventures of Bullwhip Griffin
Rating: 6.5
duration: 108 min
number_of_reviews: 678
----------------------
Movie title: Monkeys, Go Home!
Rating: 5.9
duration: 101 min
number_of_reviews: 422
----------------------
Movie title: Never a Dull Moment
Rating: 6.2
duration: 99 min
number_of_reviews: 581
----------------------
Movie title: Blackbeard's Ghost
Rating: 6.9
duration: 106 min
number_of_reviews: 4,908
----------------------
Movie title: The Love Bug
Rating: 6.5
duration: 108 min
number_of_reviews: 13,616
----------------------
Movie title: The One and Only, Genuine, Original Family Band
Rating: 6.4
duration: 110 min

number_of_reviews: 753
----------------------
Movie title: The Horse in the Gray Flannel Suit
Rating: 6.5
duration: 113 min
number_of_reviews: 835
----------------------
Movie title: The Horse in the Gray Flannel Suit
Rating: 6.5
duration: 113 min
number_of_reviews: 835
----------------------
Movie title: The Computer Wore Tennis Shoes
Rating: 6
duration: 91 min
number_of_reviews: 4,209
----------------------
Movie title: Rascal
Rating: 6.5
duration: 85 min
number_of_reviews: 377
----------------------
Movie title: Smith!
Rating: 5.9
duration: 112 min
number_of_reviews: 172
----------------------
Movie title: Smoke
Rating: 6.8
duration: 89 min
number_of_reviews: 104
----------------------
Movie title: The Aristocats
Rating: 7.1
duration: 78 min
number_of_reviews: 88,910
----------------------
Movie title: The Wild Country
Rating: 6.4
duration: 100 min
number_of_reviews: 240
----------------------
Movie title: King of the Grizzlies
Rating: 5.8
duration: 93 min
number_of_reviews: 139
----------------------
Movie title: The Boatniks
Rating: 5.5
duration: 99 min
number_of_reviews: 649
----------------------
Movie title: The Million Dollar Duck
Rating: 5.9
duration: 89 min
number_of_reviews: 1,866
----------------------
Movie title: Bedknobs and Broomsticks
Rating: 7.1
duration: 117 min
number_of_reviews: 32,680
----------------------
Movie title: Scandalous John
Rating: 6.2
duration: 113 min
number_of_reviews: 99
----------------------
Movie title: The Barefoot Executive
Rating: 6
duration: 96 min
number_of_reviews: 1,616
----------------------
Movie title: Chandar, the Black Leopard of Ceylon
Rating: 6.4
duration: 90 min
number_of_reviews: 20
----------------------
Movie title: Run, Cougar, Run
Rating: 6.4
duration: 87 min
number_of_reviews: 64
----------------------
Movie title: Napoleon and Samantha
Rating: 6.1
duration: 92 min
number_of_reviews: 820

C:\Users\USER\anaconda3\lib\site-packages\splinter\driver\webdriver\__init__.py:528: FutureWarning: browser.find_link_by_partial_text is deprecated. Use browser.links.find_by_partial_text instead.
  FutureWarning,

----------------------
Movie title: Snow White and the Seven Dwarfs
Rating: 7.6
duration: 83 min
number_of_reviews: 173,805
----------------------
Movie title: Pinocchio
Rating: 7.4
duration: 88 min
number_of_reviews: 124,575
----------------------
Movie title: Fantasia
Rating: 7.8
duration: 125 min
number_of_reviews: 85,242
----------------------
Movie title: The Reluctant Dragon
Rating: 6.9
duration: 74 min
number_of_reviews: 2,448
----------------------
Movie title: Dumbo
Rating: 7.2
duration: 64 min
number_of_reviews: 114,587
----------------------
Movie title: Bambi
Rating: 7.3
duration: 70 min
number_of_reviews: 125,811
----------------------
Movie title: Saludos Amigos
Rating: 6.2
duration: 42 min
number_of_reviews: 4,784
----------------------
Movie title: Victory Through Air Power
Rating: 6.6
duration: 70 min
number_of_reviews: 825
----------------------
Movie title: The Three Caballeros
Rating: 6.5
duration: 71 min
number_of_reviews: 11,476
----------------------
Movie title: Make Mine Music
Rating: 6.3
duration: 75 min
number_of_reviews: 3,443
----------------------
Movie title: Song of the South
Rating: 7.1
duration: 94 min
number_of_reviews: 10,684
----------------------
Movie title: Fun and Fancy Free
Rating: 6.6
duration: 73 min
number_of_reviews: 6,468
----------------------
Movie title: So Dear to My Heart
Rating: 6.8
duration: 79 min
number_of_reviews: 1,205
----------------------
Movie title: Melody Time
Rating: 6.4
duration: 75 min
number_of_reviews: 4,489
----------------------
Movie title: The Adventures of Ichabod and Mr. Toad
Rating: 7
duration: 68 min
number_of_reviews: 11,864
----------------------
Movie title: Treasure Island
Rating: 6.9
duration: 96 min
number_of_reviews: 6,603
----------------------
Movie title: Cinderella
Rating: 7.3
duration: 74 min
number_of_reviews: 139,385
----------------------
Movie title: Alice in Wonderland
Rating: 7.4
duration: 75 min
number_of_reviews: 123,371
----------------------
Movie title: The Story of Robin Hood and His Merrie Men
Rating: 6.7
duration: 84 min
number_of_reviews: 1,330
----------------------
Movie title: Peter Pan
Rating: 7.3
duration: 77 min
number_of_reviews: 120,322
----------------------
Movie title: Rob Roy: The Highland Rogue
Rating: 6.3
duration: 81 min
number_of_reviews: 476
----------------------
Movie title: The Sword and the Rose
Rating: 6.5
duration: 92 min
number_of_reviews: 704
----------------------
Movie title: 20,000 Leagues Under the Sea
Rating: 7.2
duration: 127 min
number_of_reviews: 27,806
----------------------
Movie title: Lady and the Tramp
Rating: 7.3
duration: 76 min
number_of_reviews: 116,978
----------------------
Movie title: The Littlest Outlaw
Rating: 6.1
duration: 73 min
number_of_reviews: 190
----------------------
Movie title: Davy Crockett: King of the Wild Frontier
Rating: 7
duration: 93 min
number_of_reviews: 3,374
----------------------
Movie title: Westward Ho, the Wagons!
Rating: 5.8
duration: 90 min
number_of_reviews: 279
----------------------
Movie title: Davy Crockett and the River Pirates
Rating: 6.8
duration: 81 min
number_of_reviews: 1,636
----------------------
Movie title: The Great Locomotive Chase
Rating: 6.9
duration: 85 min
number_of_reviews: 1,003
----------------------
Movie title: Old Yeller
Rating: 7.3
duration: 83 min
number_of_reviews: 11,224
----------------------
Movie title: Johnny Tremain
Rating: 6.5
duration: 80 min
number_of_reviews: 1,522
----------------------
Movie title: Tonka
Rating: 6.5
duration: 97 min
number_of_reviews: 351
----------------------
Movie title: The Light in the Forest
Rating: 6.4
duration: 83 min
number_of_reviews: 489
----------------------
Movie title: The Shaggy Dog
Rating: 6.5
duration: 104 min
number_of_reviews: 4,153
----------------------
Movie title: Sleeping Beauty
Rating: 7.2
duration: 75 min
number_of_reviews: 129,674
----------------------
Movie title: Third Man on the Mountain
Rating: 7.2
duration: 107 min
number_of_reviews: 767
----------------------
Movie title: Darby O'Gill and the Little People
Rating: 7.2
duration: 93 min
number_of_reviews: 6,668
----------------------
Movie title: Swiss Family Robinson
Rating: 7.2
duration: 126 min
number_of_reviews: 13,342
----------------------
Movie title: Ten Who Dared
Rating: 5.7
duration: 92 min
number_of_reviews: 193
----------------------
Movie title: Kidnapped
Rating: 6.6
duration: 97 min
number_of_reviews: 1,235
----------------------
Movie title: Toby Tyler or Ten Weeks with a Circus
Rating: 7
duration: 96 min
number_of_reviews: 823
----------------------
Movie title: Pollyanna
Rating: 7.4
duration: 134 min
number_of_reviews: 8,619
----------------------
Movie title: The Sign of Zorro
Rating: 7.1
duration: 91 min
number_of_reviews: 669
----------------------
Movie title: The Absent Minded Professor
Rating: 6.8
duration: 92 min
number_of_reviews: 6,969
----------------------
Movie title: Greyfriars Bobby: The True Story of a Dog
Rating: 7.3
duration: 87 min
number_of_reviews: 1,203
----------------------
Movie title: The Parent Trap
Rating: 7.1
duration: 129 min
number_of_reviews: 17,989
----------------------
Movie title: Babes in Toyland
Rating: 6.3
duration: 106 min
number_of_reviews: 3,244
----------------------
Movie title: One Hundred and One Dalmatians
Rating: 7.2
duration: 79 min
number_of_reviews: 146,163
----------------------
Movie title: In Search of the Castaways
Rating: 6.6
duration: 98 min
number_of_reviews: 2,674
----------------------
Movie title: The Legend of Lobo
Rating: 7
duration: 67 min
number_of_reviews: 432
----------------------
Movie title: Almost Angels
Rating: 6.7
duration: 93 min
number_of_reviews: 357
----------------------
Movie title: Big Red
Rating: 6.4
duration: 89 min
number_of_reviews: 653
----------------------
Movie title: Moon Pilot
Rating: 5.4
duration: 98 min
number_of_reviews: 355
----------------------
Movie title: Bon Voyage!
Rating: 5.8
duration: 130 min
number_of_reviews: 545
----------------------
Movie title: Miracle of the White Stallions
Rating: 6.6
duration: 93 min
number_of_reviews: 534
----------------------
Movie title: Summer Magic
Rating: 7
duration: 110 min
number_of_reviews: 2,056
----------------------
Movie title: Savage Sam
Rating: 6.3
duration: 103 min
number_of_reviews: 888
----------------------
Movie title: The Incredible Journey
Rating: 7.1
duration: 80 min
number_of_reviews: 3,725
----------------------
Movie title: The Sword in the Stone
Rating: 7.2
duration: 79 min
number_of_reviews: 85,363
----------------------
Movie title: Son of Flubber
Rating: 6.1
duration: 100 min
number_of_reviews: 2,561
----------------------
Movie title: Mary Poppins
Rating: 7.8
duration: 139 min
number_of_reviews: 151,423
----------------------
Movie title: A Tiger Walks
Rating: 6.4
duration: 91 min
number_of_reviews: 260
----------------------
Movie title: The Misadventures of Merlin Jones
Rating: 6.4
duration: 91 min
number_of_reviews: 613
----------------------
Movie title: The Three Lives of Thomasina
Rating: 7.2
duration: 97 min
number_of_reviews: 2,058
----------------------
Movie title: The Moon-Spinners
Rating: 6.7
duration: 118 min
number_of_reviews: 1,998
----------------------
Movie title: Emil and the Detectives
Rating: 6.2
duration: 99 min
number_of_reviews: 444
----------------------
Movie title: That Darn Cat!
Rating: 6.8
duration: 116 min
number_of_reviews: 5,576
----------------------
Movie title: The Monkey's Uncle
Rating: 6.1
duration: 87 min
number_of_reviews: 707
----------------------
Movie title: Those Calloways
Rating: 6.7
duration: 131 min
number_of_reviews: 474
----------------------
Movie title: The Ugly Dachshund
Rating: 6.7
duration: 93 min
number_of_reviews: 3,287
----------------------
Movie title: Follow Me, Boys!
Rating: 7.2
duration: 131 min
number_of_reviews: 2,038
----------------------
Movie title: The Fighting Prince of Donegal
Rating: 6.2
duration: 110 min
number_of_reviews: 320
----------------------
Movie title: Lt. Robin Crusoe, U.S.N.
Rating: 6.1
duration: 110 min
number_of_reviews: 1,183
----------------------
Movie title: The Jungle Book
Rating: 7.6
duration: 78 min
number_of_reviews: 159,308
----------------------
Movie title: The Happiest Millionaire
Rating: 6.9
duration: 141 min
number_of_reviews: 1,705
----------------------
Movie title: Charlie, the Lonesome Cougar
Rating: 6.9
duration: 75 min
number_of_reviews: 759
----------------------
Movie title: The Gnome-Mobile
Rating: 6.6
duration: 84 min
number_of_reviews: 1,891
----------------------
Movie title: The Adventures of Bullwhip Griffin
Rating: 6.5
duration: 108 min
number_of_reviews: 678
----------------------
Movie title: Monkeys, Go Home!
Rating: 5.9
duration: 101 min
number_of_reviews: 422
----------------------
Movie title: Never a Dull Moment
Rating: 6.2
duration: 99 min
number_of_reviews: 581
----------------------
Movie title: Blackbeard's Ghost
Rating: 6.9
duration: 106 min
number_of_reviews: 4,908
----------------------
Movie title: The Love Bug
Rating: 6.5
duration: 108 min
number_of_reviews: 13,616
----------------------
Movie title: The One and Only, Genuine, Original Family Band
Rating: 6.4
duration: 110 min
number_of_reviews: 753
----------------------
Movie title: The Horse in the Gray Flannel Suit
Rating: 6.5
duration: 113 min
number_of_reviews: 835
----------------------
Movie title: The Horse in the Gray Flannel Suit
Rating: 6.5
duration: 113 min
number_of_reviews: 835
----------------------
Movie title: The Computer Wore Tennis Shoes
Rating: 6
duration: 91 min
number_of_reviews: 4,209
----------------------
Movie title: Rascal
Rating: 6.5
duration: 85 min
number_of_reviews: 377
----------------------
Movie title: Smith!
Rating: 5.9
duration: 112 min
number_of_reviews: 172
----------------------
Movie title: Smoke
Rating: 6.8
duration: 89 min
number_of_reviews: 104
----------------------
Movie title: The Aristocats
Rating: 7.1
duration: 78 min
number_of_reviews: 88,910
----------------------
Movie title: The Wild Country
Rating: 6.4
duration: 100 min
number_of_reviews: 240
----------------------
Movie title: King of the Grizzlies
Rating: 5.8
duration: 93 min
number_of_reviews: 139
----------------------
Movie title: The Boatniks
Rating: 5.5
duration: 99 min
number_of_reviews: 649
----------------------
Movie title: The Million Dollar Duck
Rating: 5.9
duration: 89 min
number_of_reviews: 1,866
----------------------
Movie title: Bedknobs and Broomsticks
Rating: 7.1
duration: 117 min
number_of_reviews: 32,680
----------------------
Movie title: Scandalous John
Rating: 6.2
duration: 113 min
number_of_reviews: 99
----------------------
Movie title: The Barefoot Executive
Rating: 6
duration: 96 min
number_of_reviews: 1,616
----------------------
Movie title: Chandar, the Black Leopard of Ceylon
Rating: 6.4
duration: 90 min
number_of_reviews: 20
----------------------
Movie title: Run, Cougar, Run
Rating: 6.4
duration: 87 min
number_of_reviews: 64
----------------------
Movie title: Napoleon and Samantha
Rating: 6.1
duration: 92 min
number_of_reviews: 820

----------------------
Movie title: Blank Check
Oops, rating not found!
duration: 93 min
number_of_reviews: 18,178
----------------------
Movie title: The Lion King
Oops, rating not found!
duration: 88 min
number_of_reviews: 899,059
----------------------
Movie title: Iron Will
Rating: 6.6
duration: 108 min
number_of_reviews: 7,086
----------------------
Movie title: Gordy
Rating: 3.8
duration: 90 min
number_of_reviews: 1,820
----------------------
Movie title: Heavyweights
Rating: 6.6
duration: 100 min
number_of_reviews: 24,179
----------------------
Movie title: Tall Tale
Rating: 5.9
duration: 96 min
number_of_reviews: 3,262
----------------------
Movie title: Man of the House
Rating: 5.2
duration: 96 min
number_of_reviews: 8,377
----------------------
Movie title: Pocahontas
Rating: 6.7
duration: 81 min
number_of_reviews: 162,357
----------------------
Movie title: Operation Dumbo Drop
Rating: 5.1
duration: 107 min
number_of_reviews: 8,239
----------------------
Movie title: A Kid in King Arthur's Court
Rating: 4.7
duration: 89 min
number_of_reviews: 5,533
----------------------
Movie title: The Big Green
Rating: 5.6
duration: 100 min
number_of_reviews: 8,831
----------------------
Movie title: Tom and Huck
Rating: 5.5
duration: 97 min
number_of_reviews: 9,529
----------------------
Movie title: A Goofy Movie
Rating: 6.8
duration: 78 min
number_of_reviews: 43,563
----------------------
Movie title: Toy Story
Rating: 8.3
duration: 81 min
number_of_reviews: 847,970
----------------------
Movie title: D3: The Mighty Ducks
Rating: 5.5
duration: 104 min
number_of_reviews: 23,658
----------------------
Movie title: The Hunchback of Notre Dame
Rating: 6.9
duration: 91 min
number_of_reviews: 135,486
----------------------
Movie title: First Kid
Rating: 5.2
duration: 101 min
number_of_reviews: 9,811
----------------------
Movie title: 101 Dalmatians
Rating: 5.7
duration: 103 min
number_of_reviews: 97,462
----------------------
Movie title: Muppet Treasure Island
Rating: 7
duration: 99 min
number_of_reviews: 20,454
----------------------
Movie title: James and the Giant Peach
Rating: 6.7
duration: 79 min
number_of_reviews: 58,081
----------------------
Movie title: Homeward Bound II: Lost in San Francisco
Rating: 5.9
duration: 88 min
number_of_reviews: 13,144
----------------------
Movie title: That Darn Cat
Rating: 4.7
duration: 89 min
number_of_reviews: 3,926
----------------------
Movie title:  The Wonderful World of Disney
Rating: 4.6
duration: 88 min
number_of_reviews: 919
----------------------
Movie title:  The Wonderful World of Disney
Rating: 6.3
duration: 91 min
number_of_reviews: 1,726
----------------------
Movie title: George of the Jungle
Rating: 5.4
duration: 92 min
number_of_reviews: 68,638
----------------------
Movie title: Hercules
Rating: 7.3
duration: 93 min
number_of_reviews: 195,165
----------------------
Movie title: Tower of Terror
Oops, rating not found!
Oops, duration not found!
Oops, number of reviews not found!
----------------------
Movie title: Flubber
Rating: 5.3
duration: 93 min
number_of_reviews: 81,652
----------------------
Movie title: Mr. Magoo
Rating: 4
duration: 87 min
number_of_reviews: 13,861
----------------------
Movie title: Beauty and the Beast: The Enchanted Christmas
Rating: 6.1
duration: 72 min
number_of_reviews: 8,604
----------------------
Movie title: Jungle 2 Jungle
Rating: 5.2
duration: 105 min
number_of_reviews: 22,078
----------------------
Movie title: RocketMan
Rating: 5.9
duration: 95 min
number_of_reviews: 8,814
----------------------
Movie title: Under Wraps
Rating: 6.5
duration: 95 min
number_of_reviews: 2,391
----------------------
Movie title: Northern Lights
Rating: 5.5
duration: 111 min
number_of_reviews: 238
----------------------
Movie title: Air Bud
Rating: 5.2
duration: 98 min
number_of_reviews: 15,910
----------------------
Movie title: You Lucky Dog
Rating: 4.7
duration: 89 min
number_of_reviews: 544
----------------------
Movie title: Halloweentown
Rating: 6.8
duration: 84 min
number_of_reviews: 11,828
----------------------
Movie title: The Wonderful Ice Cream Suit
Rating: 6.3
duration: 77 min
number_of_reviews: 559
----------------------
Movie title: Meet the Deedles
Rating: 4.1
duration: 93 min
number_of_reviews: 2,594
----------------------
Movie title:  The Wonderful World of Disney
Rating: 4.8
duration: 90 min
number_of_reviews: 1,966
----------------------
Movie title: Mulan
Rating: 7.6
duration: 88 min
number_of_reviews: 238,653
----------------------
Movie title: The Parent Trap
Rating: 6.5
duration: 128 min
number_of_reviews: 114,558
----------------------
Movie title: Pocahontas II: Journey to a New World
Rating: 4.9
duration: 72 min
number_of_reviews: 13,134
----------------------
Movie title: Air Bud: Golden Receiver
Rating: 4.5
duration: 90 min
number_of_reviews: 5,178
----------------------
Movie title: I'll Be Home for Christmas
Rating: 5.5
duration: 86 min
number_of_reviews: 8,830
----------------------
Movie title: Mighty Joe Young
Rating: 5.6
duration: 114 min
number_of_reviews: 26,796
----------------------
Movie title: Brink!
Rating: 7.1
duration: 99 min
number_of_reviews: 5,329
----------------------
Movie title: A Bug's Life
Rating: 7.2
duration: 95 min
number_of_reviews: 257,446
----------------------
Movie title: The Lion King 2: Simba's Pride
Rating: 6.5
duration: 81 min
number_of_reviews: 58,382
----------------------
Movie title:  The Wonderful World of Disney
Rating: 6.6
duration: 90 min
number_of_reviews: 4,853
----------------------
Movie title: Don't Look Under the Bed
Rating: 6.9
duration: 100 min
number_of_reviews: 2,432
----------------------
Movie title: Genius
Rating: 6.3
duration: 82 min
number_of_reviews: 1,617
----------------------
Movie title: The Thirteenth Year
Rating: 6
duration: 95 min
number_of_reviews: 4,525
----------------------
Movie title: Johnny Tsunami
Rating: 6.3
duration: 88 min
number_of_reviews: 4,588
----------------------
Movie title: Can of Worms
Rating: 5
duration: 90 min
number_of_reviews: 762
----------------------
Movie title: Zenon: Girl of the 21st Century
Rating: 6.4
duration: 97 min
number_of_reviews: 6,386
----------------------
Movie title: Horse Sense
Rating: 6.2
duration: 92 min
number_of_reviews: 1,528
----------------------
Movie title: Endurance
Rating: 6.1
duration: 83 min
number_of_reviews: 364
----------------------
Movie title: Smart House
Rating: 6.3
duration: 82 min
number_of_reviews: 5,988
----------------------
Movie title: My Favorite Martian
Rating: 5.1
duration: 94 min
number_of_reviews: 12,483
----------------------
Movie title: Doug's 1st Movie
Rating: 5
duration: 77 min
number_of_reviews: 2,872
----------------------
Movie title: The Straight Story
Rating: 8
duration: 112 min
number_of_reviews: 78,156
----------------------
Movie title: Tarzan
Rating: 7.3
duration: 88 min
number_of_reviews: 194,046
----------------------
Movie title: Inspector Gadget
Rating: 4.1
duration: 78 min
number_of_reviews: 43,909
----------------------
Movie title:  The Wonderful World of Disney
Rating: 6.4
duration: 96 min
number_of_reviews: 889
----------------------
Movie title: Mickey's Once Upon a Christmas
Rating: 7.2
duration: 66 min
number_of_reviews: 6,209
----------------------
Movie title: Fantasia 2000
Rating: 7.2
duration: 75 min
number_of_reviews: 33,650
----------------------
Movie title: Toy Story 2
Rating: 7.9
duration: 92 min
number_of_reviews: 505,505
----------------------
Movie title:  The Wonderful World of Disney
Rating: 4.9
duration: 87 min
number_of_reviews: 480
----------------------
Movie title: The Ultimate Christmas Present
Rating: 5.9
duration: 85 min
number_of_reviews: 1,475
----------------------
Movie title: Phantom of the Megaplex
Rating: 6.5
duration: 89 min
number_of_reviews: 2,664
----------------------
Movie title: Mom's Got a Date with a Vampire
Rating: 5.9
duration: 85 min
number_of_reviews: 3,339
----------------------
Movie title: The Other Me
Rating: 6.1
duration: 90 min
number_of_reviews: 1,849
----------------------
Movie title: Quints
Rating: 5.6
duration: 83 min
number_of_reviews: 2,073
----------------------
Movie title: Ready to Run
Rating: 5.3
duration: 96 min
number_of_reviews: 286
----------------------
Movie title: Stepsister from Planet Weird
Rating: 6
duration: 85 min
number_of_reviews: 1,327
----------------------
Movie title: Miracle in Lane 2
Rating: 6
duration: 120 min
number_of_reviews: 1,871
----------------------
Movie title: Rip Girls
Rating: 6.2
duration: 87 min
number_of_reviews: 1,135
----------------------
Movie title: Alley Cats Strike
Rating: 6.1
duration: 103 min
number_of_reviews: 1,895
----------------------
Movie title: The Color of Friendship
Rating: 7.2
duration: 87 min
number_of_reviews: 3,277
----------------------
Movie title: Up, Up, and Away!
Rating: 5.6
duration: 90 min
number_of_reviews: 1,730
----------------------
Movie title: Air Bud 3
Rating: 4.6
duration: 83 min
number_of_reviews: 2,597
----------------------
Movie title: An Extremely Goofy Movie
Rating: 6.4
duration: 79 min
number_of_reviews: 9,293
----------------------
Movie title: Whispers: An Elephant's Tale
Rating: 5
duration: 72 min
number_of_reviews: 265
----------------------
Movie title: Dinosaur
Rating: 6.5
duration: 82 min
number_of_reviews: 50,739
----------------------
Movie title: The Kid
Rating: 6.1
duration: 104 min
number_of_reviews: 39,196
----------------------
Movie title: The Little Mermaid 2: Return to the Sea
Rating: 5.6
duration: 75 min
number_of_reviews: 16,552
----------------------
Movie title: Remember the Titans
Rating: 7.8
duration: 113 min
number_of_reviews: 190,948
----------------------
Movie title: 102 Dalmatians
Rating: 4.9
duration: 100 min
number_of_reviews: 33,488
----------------------
Movie title:  The Wonderful World of Disney
Rating: 5.1
duration: 89 min
number_of_reviews: 364
----------------------
Movie title:  The Wonderful World of Disney
Rating: 5.4
duration: 89 min
number_of_reviews: 658
----------------------
Movie title: The Emperor's New Groove
Rating: 7.3
duration: 78 min
number_of_reviews: 171,235
----------------------
Movie title: The Tigger Movie
Rating: 6.3
duration: 77 min
number_of_reviews: 16,480
----------------------
Movie title: Jett Jackson: The Movie
Rating: 6.2
duration: 100 min
number_of_reviews: 1,133
----------------------
Movie title: Mickey's Magical Christmas: Snowed in at the House of Mouse
Rating: 6.7
duration: 65 min
number_of_reviews: 2,781
----------------------
Movie title: Motocrossed
Rating: 6.6
duration: 110 min
number_of_reviews: 4,338
----------------------
Movie title: Recess: School's Out
Rating: 6.6
duration: 82 min
number_of_reviews: 9,046
----------------------
Movie title: Lady and the Tramp 2: Scamp's Adventure
Rating: 5.9

duration: 69 min
number_of_reviews: 9,989
----------------------
Movie title: Atlantis: The Lost Empire
Rating: 6.9
duration: 95 min
number_of_reviews: 98,604
----------------------
Movie title: Spirited Away
Rating: 8.6
duration: 125 min
number_of_reviews: 605,234
----------------------
Movie title: Blank Check
Oops, rating not found!
duration: 93 min
number_of_reviews: 18,178
----------------------
Movie title: The Lion King
Oops, rating not found!
duration: 88 min
number_of_reviews: 899,059
----------------------
Movie title: Iron Will
Rating: 6.6
duration: 108 min
number_of_reviews: 7,086
----------------------
Movie title: Gordy
Rating: 3.8
duration: 90 min
number_of_reviews: 1,820
----------------------
Movie title: Heavyweights
Rating: 6.6
duration: 100 min
number_of_reviews: 24,179
----------------------
Movie title: Tall Tale
Rating: 5.9
duration: 96 min
number_of_reviews: 3,262
----------------------
Movie title: Man of the House
Rating: 5.2
duration: 96 min
number_of_reviews: 8,377
----------------------
Movie title: Pocahontas
Rating: 6.7
duration: 81 min
number_of_reviews: 162,357
----------------------
Movie title: Operation Dumbo Drop
Rating: 5.1
duration: 107 min
number_of_reviews: 8,239
----------------------
Movie title: A Kid in King Arthur's Court
Rating: 4.7
duration: 89 min
number_of_reviews: 5,533
----------------------
Movie title: The Big Green
Rating: 5.6
duration: 100 min
number_of_reviews: 8,831
----------------------
Movie title: Tom and Huck
Rating: 5.5
duration: 97 min
number_of_reviews: 9,529
----------------------
Movie title: A Goofy Movie
Rating: 6.8
duration: 78 min
number_of_reviews: 43,563
----------------------
Movie title: Toy Story
Rating: 8.3
duration: 81 min
number_of_reviews: 847,970
----------------------
Movie title: D3: The Mighty Ducks
Rating: 5.5
duration: 104 min
number_of_reviews: 23,658
----------------------
Movie title: The Hunchback of Notre Dame
Rating: 6.9
duration: 91 min
number_of_reviews: 135,486
----------------------
Movie title: First Kid
Rating: 5.2
duration: 101 min
number_of_reviews: 9,811
----------------------
Movie title: 101 Dalmatians
Rating: 5.7
duration: 103 min
number_of_reviews: 97,462
----------------------
Movie title: Muppet Treasure Island
Rating: 7
duration: 99 min
number_of_reviews: 20,454
----------------------
Movie title: James and the Giant Peach
Rating: 6.7
duration: 79 min
number_of_reviews: 58,081
----------------------
Movie title: Homeward Bound II: Lost in San Francisco
Rating: 5.9
duration: 88 min
number_of_reviews: 13,144
----------------------
Movie title: That Darn Cat
Rating: 4.7
duration: 89 min
number_of_reviews: 3,926
----------------------
Movie title:  The Wonderful World of Disney
Rating: 4.6
duration: 88 min
number_of_reviews: 919
----------------------
Movie title:  The Wonderful World of Disney
Rating: 6.3
duration: 91 min
number_of_reviews: 1,726
----------------------
Movie title: George of the Jungle
Rating: 5.4
duration: 92 min
number_of_reviews: 68,638
----------------------
Movie title: Hercules
Rating: 7.3
duration: 93 min
number_of_reviews: 195,165
----------------------
Movie title: Tower of Terror
Oops, rating not found!
Oops, duration not found!
Oops, number of reviews not found!
----------------------
Movie title: Flubber
Rating: 5.3
duration: 93 min
number_of_reviews: 81,652
----------------------
Movie title: Mr. Magoo
Rating: 4
duration: 87 min
number_of_reviews: 13,861
----------------------
Movie title: Beauty and the Beast: The Enchanted Christmas
Rating: 6.1
duration: 72 min
number_of_reviews: 8,604
----------------------
Movie title: Jungle 2 Jungle
Rating: 5.2
duration: 105 min
number_of_reviews: 22,078
----------------------
Movie title: RocketMan
Rating: 5.9
duration: 95 min
number_of_reviews: 8,814
----------------------
Movie title: Under Wraps
Rating: 6.5
duration: 95 min
number_of_reviews: 2,391
----------------------
Movie title: Northern Lights
Rating: 5.5
duration: 111 min
number_of_reviews: 238
----------------------
Movie title: Air Bud
Rating: 5.2
duration: 98 min
number_of_reviews: 15,910
----------------------
Movie title: You Lucky Dog
Rating: 4.7
duration: 89 min
number_of_reviews: 544
----------------------
Movie title: Halloweentown
Rating: 6.8
duration: 84 min
number_of_reviews: 11,828
----------------------
Movie title: The Wonderful Ice Cream Suit
Rating: 6.3
duration: 77 min
number_of_reviews: 559
----------------------
Movie title: Meet the Deedles
Rating: 4.1
duration: 93 min
number_of_reviews: 2,594
----------------------
Movie title:  The Wonderful World of Disney
Rating: 4.8
duration: 90 min
number_of_reviews: 1,966
----------------------
Movie title: Mulan
Rating: 7.6
duration: 88 min
number_of_reviews: 238,653
----------------------
Movie title: The Parent Trap
Rating: 6.5
duration: 128 min
number_of_reviews: 114,558
----------------------
Movie title: Pocahontas II: Journey to a New World
Rating: 4.9
duration: 72 min
number_of_reviews: 13,134
----------------------
Movie title: Air Bud: Golden Receiver
Rating: 4.5
duration: 90 min
number_of_reviews: 5,178
----------------------
Movie title: I'll Be Home for Christmas
Rating: 5.5
duration: 86 min
number_of_reviews: 8,830
----------------------
Movie title: Mighty Joe Young
Rating: 5.6
duration: 114 min
number_of_reviews: 26,796
----------------------
Movie title: Brink!
Rating: 7.1
duration: 99 min
number_of_reviews: 5,329
----------------------
Movie title: A Bug's Life
Rating: 7.2
duration: 95 min
number_of_reviews: 257,446
----------------------
Movie title: The Lion King 2: Simba's Pride
Rating: 6.5
duration: 81 min
number_of_reviews: 58,382
----------------------
Movie title:  The Wonderful World of Disney
Rating: 6.6
duration: 90 min
number_of_reviews: 4,853
----------------------
Movie title: Don't Look Under the Bed
Rating: 6.9
duration: 100 min
number_of_reviews: 2,432
----------------------
Movie title: Genius
Rating: 6.3
duration: 82 min
number_of_reviews: 1,617
----------------------
Movie title: The Thirteenth Year
Rating: 6
duration: 95 min
number_of_reviews: 4,525
----------------------
Movie title: Johnny Tsunami
Rating: 6.3
duration: 88 min
number_of_reviews: 4,588
----------------------
Movie title: Can of Worms
Rating: 5
duration: 90 min
number_of_reviews: 762
----------------------
Movie title: Zenon: Girl of the 21st Century
Rating: 6.4
duration: 97 min
number_of_reviews: 6,386
----------------------
Movie title: Horse Sense
Rating: 6.2
duration: 92 min
number_of_reviews: 1,528
----------------------
Movie title: Endurance
Rating: 6.1
duration: 83 min
number_of_reviews: 364
----------------------
Movie title: Smart House
Rating: 6.3
duration: 82 min
number_of_reviews: 5,988
----------------------
Movie title: My Favorite Martian
Rating: 5.1
duration: 94 min
number_of_reviews: 12,483
----------------------
Movie title: Doug's 1st Movie
Rating: 5
duration: 77 min
number_of_reviews: 2,872
----------------------
Movie title: The Straight Story
Rating: 8
duration: 112 min
number_of_reviews: 78,156
----------------------
Movie title: Tarzan
Rating: 7.3
duration: 88 min
number_of_reviews: 194,046
----------------------
Movie title: Inspector Gadget
Rating: 4.1
duration: 78 min
number_of_reviews: 43,909
----------------------
Movie title:  The Wonderful World of Disney
Rating: 6.4
duration: 96 min
number_of_reviews: 889
----------------------
Movie title: Mickey's Once Upon a Christmas
Rating: 7.2
duration: 66 min
number_of_reviews: 6,209
----------------------
Movie title: Fantasia 2000
Rating: 7.2
duration: 75 min
number_of_reviews: 33,650
----------------------
Movie title: Toy Story 2
Rating: 7.9
duration: 92 min
number_of_reviews: 505,505
----------------------
Movie title:  The Wonderful World of Disney
Rating: 4.9
duration: 87 min
number_of_reviews: 480
----------------------
Movie title: The Ultimate Christmas Present
Rating: 5.9
duration: 85 min
number_of_reviews: 1,475
----------------------
Movie title: Phantom of the Megaplex
Rating: 6.5
duration: 89 min
number_of_reviews: 2,664
----------------------
Movie title: Mom's Got a Date with a Vampire
Rating: 5.9
duration: 85 min
number_of_reviews: 3,339
----------------------
Movie title: The Other Me
Rating: 6.1
duration: 90 min
number_of_reviews: 1,849
----------------------
Movie title: Quints
Rating: 5.6
duration: 83 min
number_of_reviews: 2,073
----------------------
Movie title: Ready to Run
Rating: 5.3
duration: 96 min
number_of_reviews: 286
----------------------
Movie title: Stepsister from Planet Weird
Rating: 6
duration: 85 min
number_of_reviews: 1,327
----------------------
Movie title: Miracle in Lane 2
Rating: 6
duration: 120 min
number_of_reviews: 1,871
----------------------
Movie title: Rip Girls
Rating: 6.2
duration: 87 min
number_of_reviews: 1,135
----------------------
Movie title: Alley Cats Strike
Rating: 6.1
duration: 103 min
number_of_reviews: 1,895
----------------------
Movie title: The Color of Friendship
Rating: 7.2
duration: 87 min
number_of_reviews: 3,277
----------------------
Movie title: Up, Up, and Away!
Rating: 5.6
duration: 90 min
number_of_reviews: 1,730
----------------------
Movie title: Air Bud 3
Rating: 4.6
duration: 83 min
number_of_reviews: 2,597
----------------------
Movie title: An Extremely Goofy Movie
Rating: 6.4
duration: 79 min
number_of_reviews: 9,293
----------------------
Movie title: Whispers: An Elephant's Tale
Rating: 5
duration: 72 min
number_of_reviews: 265
----------------------
Movie title: Dinosaur
Rating: 6.5
duration: 82 min
number_of_reviews: 50,739
----------------------
Movie title: The Kid
Rating: 6.1
duration: 104 min
number_of_reviews: 39,196
----------------------
Movie title: The Little Mermaid 2: Return to the Sea
Rating: 5.6
duration: 75 min
number_of_reviews: 16,552
----------------------
Movie title: Remember the Titans
Rating: 7.8
duration: 113 min
number_of_reviews: 190,948
----------------------
Movie title: 102 Dalmatians
Rating: 4.9
duration: 100 min
number_of_reviews: 33,488
----------------------
Movie title:  The Wonderful World of Disney
Rating: 5.1
duration: 89 min
number_of_reviews: 364
----------------------
Movie title:  The Wonderful World of Disney
Rating: 5.4
duration: 89 min
number_of_reviews: 658
----------------------
Movie title: The Emperor's New Groove
Rating: 7.3
duration: 78 min
number_of_reviews: 171,235
----------------------
Movie title: The Tigger Movie
Rating: 6.3
duration: 77 min
number_of_reviews: 16,480
----------------------
Movie title: Jett Jackson: The Movie
Rating: 6.2
duration: 100 min
number_of_reviews: 1,133
----------------------
Movie title: Mickey's Magical Christmas: Snowed in at the House of Mouse
Rating: 6.7
duration: 65 min
number_of_reviews: 2,781
----------------------
Movie title: Motocrossed
Rating: 6.6
duration: 110 min
number_of_reviews: 4,338
----------------------
Movie title: Recess: School's Out
Rating: 6.6
duration: 82 min
number_of_reviews: 9,046
----------------------
Movie title: Lady and the Tramp 2: Scamp's Adventure
Rating: 5.9
duration: 69 min
number_of_reviews: 9,989
----------------------
Movie title: Atlantis: The Lost Empire
Rating: 6.9
duration: 95 min
number_of_reviews: 98,604
----------------------
Movie title: Spirited Away
Rating: 8.6
duration: 125 min
number_of_reviews: 605,234

----------------------
Movie title: The Princess Diaries
Oops, rating not found!
duration: 111 min
number_of_reviews: 122,454
----------------------
Movie title: Max Keeble's Big Move
Oops, rating not found!
duration: 86 min
number_of_reviews: 7,128
----------------------
Movie title: Monsters, Inc.
Rating: 8
duration: 92 min
number_of_reviews: 781,434
----------------------
Movie title: 'Twas the Night
Rating: 5.5
duration: 84 min
number_of_reviews: 764
----------------------
Movie title: The Other Side of Heaven
Rating: 6.4
duration: 113 min
number_of_reviews: 3,972
----------------------
Movie title: Halloweentown II: Kalabar's Revenge
Rating: 6.5
duration: 81 min
number_of_reviews: 6,522
----------------------
Movie title: The Poof Point
Rating: 4.7
duration: 90 min
number_of_reviews: 489
----------------------
Movie title: Jumping Ship
Rating: 6.2
duration: 93 min
number_of_reviews: 1,599
----------------------
Movie title: The Jennie Project
Rating: 5.3
duration: 76 min
number_of_reviews: 215
----------------------
Movie title: Hounded
Rating: 5.1
duration: 91 min
number_of_reviews: 906
----------------------
Movie title: The Luck of the Irish
Rating: 6.2
duration: 86 min
number_of_reviews: 6,360
----------------------
Movie title: Zenon: The Zequel
Rating: 5.9
duration: 100 min
number_of_reviews: 3,358
----------------------
Movie title: The Scream Team
Rating: 6.7
duration: 100 min
number_of_reviews: 823
----------------------
Movie title: A Ring of Endless Light
Rating: 6.1
duration: 88 min
number_of_reviews: 1,041
----------------------
Movie title: Gotta Kick It Up!
Rating: 5.8
duration: 78 min
number_of_reviews: 1,584
----------------------
Movie title: Get a Clue
Rating: 5.1
duration: 83 min
number_of_reviews: 5,701
----------------------
Movie title: Tru Confessions
Rating: 7.5
duration: 112 min
number_of_reviews: 2,884
----------------------
Movie title: Cadet Kelly
Rating: 5.5
duration: 101 min
number_of_reviews: 12,670
----------------------
Movie title: Double Teamed
Rating: 6.1
duration: 120 min
number_of_reviews: 3,023
----------------------
Movie title: Air Bud: Seventh Inning Fetch
Rating: 4.5
duration: 93 min
number_of_reviews: 1,898
----------------------
Movie title: Snow Dogs
Rating: 5.2
duration: 99 min
number_of_reviews: 24,495
----------------------
Movie title: Peter Pan 2: Return to Never Land
Rating: 5.8
duration: 72 min
number_of_reviews: 17,574
----------------------
Movie title: Cinderella 2: Dreams Come True
Rating: 5
duration: 73 min
number_of_reviews: 9,985
----------------------
Movie title: Lilo & Stitch
Rating: 7.2
duration: 85 min
number_of_reviews: 159,954
----------------------
Movie title: The Country Bears
Rating: 4.1
duration: 88 min
number_of_reviews: 4,841
----------------------
Movie title: Tuck Everlasting
Rating: 6.6
duration: 90 min
number_of_reviews: 20,563
----------------------
Movie title: The Santa Clause 2
Rating: 5.6
duration: 104 min
number_of_reviews: 47,840
----------------------
Movie title: Treasure Planet
Rating: 7.2
duration: 95 min
number_of_reviews: 96,776
----------------------
Movie title: Winnie the Pooh: A Very Merry Pooh Year
Rating: 6.8
duration: 65 min
number_of_reviews: 1,797
----------------------
Movie title: The Rookie
Rating: 6.9
duration: 127 min
number_of_reviews: 31,132
----------------------
Movie title: Kim Possible: A Sitch in Time
Rating: 7
duration: 66 min
number_of_reviews: 3,826
----------------------
Movie title: Full-Court Miracle
Rating: 5.8
duration: 90 min
number_of_reviews: 850
----------------------
Movie title: The Cheetah Girls
Rating: 4.8
duration: 100 min
number_of_reviews: 6,834
----------------------
Movie title: Eddie's Million Dollar Cook-Off
Rating: 6
duration: 110 min
number_of_reviews: 2,396
----------------------
Movie title: The Even Stevens Movie
Rating: 6.2
duration: 93 min
number_of_reviews: 6,284
----------------------
Movie title: Right on Track
Rating: 6.2
duration: 89 min
number_of_reviews: 1,121
----------------------
Movie title: You Wish!
Rating: 6.1
duration: 84 min
number_of_reviews: 1,650
----------------------
Movie title: Air Bud: Spikes Back
Rating: 4.1
duration: 87 min
number_of_reviews: 1,686
----------------------
Movie title: Brother Bear
Rating: 6.8
duration: 85 min
number_of_reviews: 92,180
----------------------
Movie title: 101 Dalmatians 2: Patch's London Adventure
Rating: 5.8
duration: 74 min
number_of_reviews: 7,413
----------------------
Movie title: The Jungle Book 2
Rating: 5.4
duration: 72 min
number_of_reviews: 14,394
----------------------
Movie title: Inspector Gadget 2
Rating: 3.4
duration: 89 min
number_of_reviews: 5,436
----------------------
Movie title: Piglet's Big Movie
Rating: 6.1
duration: 75 min
number_of_reviews: 6,526
----------------------
Movie title: Holes
Rating: 7
duration: 117 min
number_of_reviews: 73,929
----------------------
Movie title: Atlantis: Milo's Return
Rating: 5.1
duration: 70 min
number_of_reviews: 7,577
----------------------
Movie title: Lizzie McGuire
Rating: 5.5
duration: 94 min
number_of_reviews: 34,532
----------------------
Movie title: Pirates of the Caribbean: The Curse of the Black Pearl
Rating: 8
duration: 143 min
number_of_reviews: 990,769
----------------------
Movie title: Freaky Friday
Rating: 6.1
duration: 97 min
number_of_reviews: 120,160
----------------------
Movie title: George of the Jungle 2
Rating: 3.3
duration: 87 min
number_of_reviews: 6,063
----------------------
Movie title: The Haunted Mansion
Rating: 5
duration: 88 min
number_of_reviews: 40,258
----------------------
Movie title: The Young Black Stallion
Rating: 5.6
duration: 50 min
number_of_reviews: 1,006
----------------------
Movie title: Finding Nemo
Rating: 8.1
duration: 100 min
number_of_reviews: 912,674
----------------------
Movie title: Going to the Mat
Rating: 6.8
duration: 120 min
number_of_reviews: 1,217
----------------------
Movie title: Pixel Perfect
Rating: 5.7
duration: 85 min
number_of_reviews: 3,129
----------------------
Movie title: Zenon: Z3
Rating: 5.5
duration: 81 min
number_of_reviews: 2,335
----------------------
Movie title: Halloweentown High
Rating: 6.2
duration: 82 min
number_of_reviews: 5,486
----------------------
Movie title: Tiger Cruise
Rating: 6.2
duration: 88 min
number_of_reviews: 1,174
----------------------
Movie title: Stuck in the Suburbs
Rating: 5.6
duration: 76 min
number_of_reviews: 3,434
----------------------
Movie title: Teacher's Pet
Rating: 5.8
duration: 73 min
number_of_reviews: 1,496
----------------------
Movie title: Miracle
Rating: 7.5
duration: 135 min
number_of_reviews: 45,837
----------------------
Movie title: Confessions of a Teenage Drama Queen
Rating: 4.6
duration: 89 min
number_of_reviews: 26,684
----------------------
Movie title: Home on the Range
Rating: 5.3
duration: 76 min
number_of_reviews: 19,121
----------------------
Movie title: Winnie the Pooh: Springtime with Roo
Rating: 6.5
duration: 65 min
number_of_reviews: 1,674
----------------------
Movie title: Around the World in 80 Days
Rating: 5.9
duration: 120 min
number_of_reviews: 81,787
----------------------
Movie title: Mickey, Donald, Goofy: The Three Musketeers
Rating: 6.4
duration: 68 min
number_of_reviews: 7,438
----------------------
Movie title: The Princess Diaries 2: Royal Engagement
Rating: 5.8
duration: 113 min
number_of_reviews: 71,064
----------------------
Movie title: Howl's Moving Castle
Rating: 8.2
duration: 119 min
number_of_reviews: 305,421
----------------------
Movie title: Mulan II
Rating: 5.7
duration: 79 min
number_of_reviews: 20,697
----------------------
Movie title: National Treasure
Rating: 6.8
duration: 131 min
number_of_reviews: 295,210
----------------------
Movie title: Mickey's Twice Upon a Christmas
Rating: 6.6
duration: 68 min
number_of_reviews: 3,764
----------------------
Movie title: The Incredibles
Rating: 8
duration: 115 min
number_of_reviews: 633,077
----------------------
Movie title: The Lion King 3: Hakuna Matata
Rating: 6.6
duration: 77 min
number_of_reviews: 35,506
----------------------
Movie title:  The Wonderful World of Disney
Rating: 6.3
duration: 90 min
number_of_reviews: 1,142
----------------------
Movie title: Kim Possible: So the Drama
Rating: 7.1
duration: 71 min
number_of_reviews: 3,748
----------------------
Movie title: Go Figure
Rating: 5.8
duration: 88 min
number_of_reviews: 3,242
----------------------
Movie title: Life Is Ruff
Rating: 4.9
duration: 84 min
number_of_reviews: 1,231
----------------------
Movie title: The Proud Family Movie
Rating: 5.4
duration: 90 min
number_of_reviews: 1,442
----------------------
Movie title: Kronk's New Groove
Rating: 5.8
duration: 75 min
number_of_reviews: 10,552
----------------------
Movie title: Twitches
Rating: 5.7
duration: 86 min
number_of_reviews: 6,684
----------------------
Movie title: The Greatest Game Ever Played
Rating: 7.4
duration: 120 min
number_of_reviews: 26,904
----------------------
Movie title: Lilo & Stitch 2: Stitch Has a Glitch
Rating: 6.3
duration: 68 min
number_of_reviews: 11,305
----------------------
Movie title: Pooh's Heffalump Movie
Rating: 6.4
duration: 68 min
number_of_reviews: 6,067
----------------------
Movie title: The Pacifier
Rating: 5.6
duration: 95 min
number_of_reviews: 84,547
----------------------
Movie title: Ice Princess
Rating: 6
duration: 98 min
number_of_reviews: 23,955
----------------------
Movie title: Sky High
Rating: 6.2
duration: 100 min
number_of_reviews: 75,687
----------------------
Movie title: Pooh's Heffalump Halloween Movie
Rating: 6.6
duration: 67 min
number_of_reviews: 842
----------------------
Movie title: Herbie Fully Loaded
Rating: 4.8
duration: 101 min
number_of_reviews: 43,740
----------------------
Movie title: Chicken Little
Rating: 5.7
duration: 81 min
number_of_reviews: 82,623
----------------------
Movie title: Valiant
Rating: 5.5
duration: 76 min
number_of_reviews: 20,176
----------------------
Movie title: The Chronicles of Narnia: The Lion, the Witch and the Wardrobe
Rating: 6.9
duration: 143 min
number_of_reviews: 353,721
----------------------
Movie title: Buffalo Dreams
Rating: 5.8
duration: 89 min
number_of_reviews: 441
----------------------
Movie title: Now You See It...
Rating: 6.3
duration: 83 min
number_of_reviews: 2,101
----------------------
Movie title: Read It and Weep
Rating: 5.5
duration: 84 min
number_of_reviews: 4,959
----------------------
Movie title: Wendy Wu: Homecoming Warrior
Rating: 5.4
duration: 91 min
number_of_reviews: 5,402
----------------------
Movie title: Cow Belles
Rating: 5.2
duration: 90 min
number_of_reviews: 5,658
----------------------
Movie title: The Cheetah Girls 2
Rating: 5
duration: 96 min
number_of_reviews: 5,516
----------------------
Movie title: Air Buddies
Rating: 4.8
duration: 80 min
number_of_reviews: 3,166
----------------------
Movie title: Return to Halloweentown
Rating: 5.6
duration: 88 min
number_of_reviews: 5,339
----------------------
Movie title: High School Musical
Rating: 5.4
duration: 98 min
number_of_reviews: 77,132
----------------------
Movie title: Brother Bear 2
Rating: 6.2
duration: 74 min
number_of_reviews: 13,843

----------------------
Movie title: Planes
Oops, rating not found!
duration: 91 min
number_of_reviews: 41,120
----------------------
Movie title: Super Buddies
Oops, rating not found!
duration: 81 min
number_of_reviews: 1,090
----------------------
Movie title: Frozen
Rating: 7.4
duration: 102 min
number_of_reviews: 552,105
----------------------
Movie title: Oz the Great and Powerful
Rating: 6.3
duration: 130 min
number_of_reviews: 195,837
----------------------
Movie title: The Lone Ranger
Rating: 6.4
duration: 150 min
number_of_reviews: 215,442
----------------------
Movie title: How to Build a Better Boy
Rating: 5.5
duration: 90 min
number_of_reviews: 2,497
----------------------
Movie title: Zapped
Rating: 5.1
duration: 102 min
number_of_reviews: 3,754
----------------------
Movie title: Cloud 9
Rating: 6.6
duration: 85 min
number_of_reviews: 3,636
----------------------
Movie title: The Pirate Fairy
Rating: 6.6
duration: 78 min
number_of_reviews: 11,669
----------------------
Movie title: Into the Woods
Rating: 5.9
duration: 125 min
number_of_reviews: 128,010
----------------------
Movie title: Alexander and the Terrible, Horrible, No Good, Very Bad Day
Rating: 6.2
duration: 81 min
number_of_reviews: 39,170
----------------------
Movie title: Million Dollar Arm
Rating: 7
duration: 124 min
number_of_reviews: 42,187
----------------------
Movie title: Planes: Fire & Rescue
Rating: 6
duration: 83 min
number_of_reviews: 15,954
----------------------
Movie title: Big Hero 6
Rating: 7.8
duration: 102 min
number_of_reviews: 393,438
----------------------
Movie title: Muppets Most Wanted
Rating: 6.4
duration: 107 min
number_of_reviews: 30,339
----------------------
Movie title: Maleficent
Rating: 7
duration: 97 min
number_of_reviews: 330,265
----------------------
Movie title: McFarland, USA
Rating: 7.4
duration: 129 min
number_of_reviews: 33,689
----------------------
Movie title: Teen Beach 2
Rating: 6.1
duration: 104 min
number_of_reviews: 3,336
----------------------
Movie title: Tinker Bell and the Legend of the NeverBeast
Rating: 7.3
duration: 76 min
number_of_reviews: 7,090
----------------------
Movie title: Bad Hair Day
Rating: 6
duration: 87 min
number_of_reviews: 2,449
----------------------
Movie title: Descendants
Rating: 6.4
duration: 112 min
number_of_reviews: 14,473
----------------------
Movie title: Tomorrowland
Rating: 6.4
duration: 130 min
number_of_reviews: 167,123
----------------------
Movie title: Inside Out
Rating: 8.2
duration: 95 min
number_of_reviews: 577,690
----------------------
Movie title: Cinderella
Rating: 6.9
duration: 105 min
number_of_reviews: 152,325
----------------------
Movie title: The Good Dinosaur
Rating: 6.7
duration: 93 min
number_of_reviews: 97,043
----------------------
Movie title: Moana
Rating: 7.6
duration: 107 min
number_of_reviews: 249,860
----------------------
Movie title: The Jungle Book
Rating: 7.4
duration: 106 min
number_of_reviews: 251,143
----------------------
Movie title: Alice Through the Looking Glass
Rating: 6.2
duration: 113 min
number_of_reviews: 86,811
----------------------
Movie title: Zootopia
Rating: 8
duration: 108 min
number_of_reviews: 411,057
----------------------
Movie title: Finding Dory
Rating: 7.3
duration: 97 min
number_of_reviews: 228,045
----------------------
Movie title: Queen of Katwe
Rating: 7.4
duration: 124 min
number_of_reviews: 14,283
----------------------
Movie title: Adventures in Babysitting
Rating: 6
duration: 105 min
number_of_reviews: 2,639
----------------------
Movie title: Pete's Dragon
Rating: 6.7
duration: 102 min
number_of_reviews: 51,912
----------------------
Movie title: The Finest Hours
Rating: 6.8
duration: 117 min
number_of_reviews: 59,200
----------------------
Movie title: The Swap
Rating: 6.1
duration: 100 min
number_of_reviews: 1,551
----------------------
Movie title: The BFG
Rating: 6.4
duration: 117 min
number_of_reviews: 73,711
----------------------
Movie title: Cars 3
Rating: 6.7
duration: 102 min
number_of_reviews: 68,249
----------------------
Movie title: Coco
Rating: 8.4
duration: 105 min
number_of_reviews: 333,466
----------------------
Movie title: Pirates of the Caribbean: Dead Men Tell No Tales
Rating: 6.6
duration: 129 min
number_of_reviews: 247,283
----------------------
Movie title: Descendants 2
Rating: 6.5
duration: 111 min
number_of_reviews: 7,218
----------------------
Movie title: Beauty and the Beast
Rating: 7.1
duration: 129 min
number_of_reviews: 257,714
----------------------
Movie title: Toy Story 4
Rating: 7.8
duration: 100 min
number_of_reviews: 175,127

In [4]:
browser.quit()

In [5]:
print(len(rating_list), len(title_list), len(duration_list), len(number_of_reviews))

542 542 542 542

In [6]:
# create a review dataframe
rating_df = pd.DataFrame({'Title': title_list,
                         'Duration': duration_list,
                         'IMDB_rating': rating_list,
                         'Number_of_Reviews': number_of_reviews})
rating_df

,Title,Duration,IMDB_rating,Number_of_Reviews
0,Snow White and the Seven Dwarfs,83 min,7.6,"173,805"
1,Pinocchio,88 min,7.4,"124,575"
2,Fantasia,125 min,7.8,"85,242"
3,The Reluctant Dragon,74 min,6.9,"2,448"
4,Dumbo,64 min,7.2,"114,587"
...,...,...,...,...
537,Coco,105 min,8.4,"333,466"
538,Pirates of the Caribbean: Dead Men Tell No Tales,129 min,6.6,"247,283"
539,Descendants 2,111 min,6.5,"7,218"
540,Beauty and the Beast,129 min,7.1,"257,714"
541,Toy Story 4,100 min,7.8,"175,127"

### Table 3 & Table 4: 
source: IMDB website https://www.imdb.com/list/ls068561553/

Extract directors and actors of each Disney movie

In [7]:
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser("chrome", **executable_path, headless=False)

In [8]:
title_list = []
director_list = []
actor_list = []

url = "https://www.imdb.com/list/ls068561553/"
browser.visit(url)


for x in range(1, 8):
    html = browser.html
    soup = bs(html, 'html.parser')
    contents = soup.find_all("div", class_='lister-item-content')
        
        
    for content in contents:
        print("----------------------")
        
        title = content.find('a').text
        print(f"Movie title: {title}")
        title_list.append(title)
        
        # find the directors and actors
        tag = content.find_all("p", class_="text-muted text-small")
        #get all of directors and voice actors
        staff_member = tag[1].text
        # remove Punctuation from text
        tag_list = ''.join([text for text in staff_member if text not in (',', '|', ":")])
        # remove space and empty strings
        tag_list_1 = [i for i in tag_list.split("\n") if i]
        tag_list_2 = [i.rstrip().lstrip() for i in tag_list_1]
        new_tag_list = [i for i in tag_list_2 if i != ""]

        #extract director and actor names
        director = []
        actor = []
        for i in range(len(new_tag_list)):
            if new_tag_list[i] == "Stars" or new_tag_list[i] == "Star":
                star_index = i
        director = new_tag_list[1 : star_index]
        actor = new_tag_list[star_index + 1:len(new_tag_list)]
        
        director_list.append(director)
        actor_list.append(actor)

        string_director=", ".join(director)
        string_actor=", ".join(actor)
        print(f"directors: {string_director}")
        print(f"actors: {string_actor}")
          
            
    time.sleep(5)
    browser.click_link_by_partial_text('Next')

----------------------
Movie title: Snow White and the Seven Dwarfs
directors: William Cottrell, David Hand, Wilfred Jackson, Larry Morey, Perce Pearce, Ben Sharpsteen
actors: Adriana Caselotti, Harry Stockwell, Lucille La Verne, Roy Atwell
----------------------
Movie title: Pinocchio
directors: Norman Ferguson, T. Hee, Wilfred Jackson, Jack Kinney, Hamilton Luske, Bill Roberts, Ben Sharpsteen
actors: Dickie Jones, Christian Rub, Mel Blanc, Don Brodie
----------------------
Movie title: Fantasia
directors: James Algar, Samuel Armstrong, Ford Beebe Jr., Norman Ferguson, David Hand, Jim Handley, T. Hee, Wilfred Jackson, Hamilton Luske, Bill Roberts, Paul Satterfield, Ben Sharpsteen
actors: Leopold Stokowski, Deems Taylor, The Philadelphia Orchestra, Corey Burton
----------------------
Movie title: The Reluctant Dragon
directors: Alfred L. Werker, Hamilton Luske, Jack Cutting, Ub Iwerks, Jack Kinney
actors: Robert Benchley, Frances Gifford, Buddy Pepper, Nana Bryant
----------------------
Movie title: Dumbo
directors: Samuel Armstrong, Norman Ferguson, Wilfred Jackson, Jack Kinney, Bill Roberts, Ben Sharpsteen, John Elliotte
actors: Sterling Holloway, Edward Brophy, Herman Bing, Billy Bletcher
----------------------
Movie title: Bambi
directors: James Algar, Samuel Armstrong, David Hand, Graham Heid, Bill Roberts, Paul Satterfield, Norman Wright, Arthur Davis, Clyde Geronimi
actors: Hardie Albright, Stan Alexander, Bobette Audrey, Peter Behn
----------------------
Movie title: Saludos Amigos
directors: Wilfred Jackson, Jack Kinney, Hamilton Luske, Bill Roberts, Norman Ferguson
actors: Fred Shields, José Oliveira, Lee Blair, Mary Blair
----------------------
Movie title: Victory Through Air Power
directors: James Algar, Clyde Geronimi, Jack Kinney, H.C. Potter
actors: Alexander de Seversky, Art Baker, Billy Mitchell
----------------------
Movie title: The Three Caballeros
directors: Norman Ferguson, Clyde Geronimi, Jack Kinney, Bill Roberts, Harold Young
actors: Aurora Miranda, Carmen Molina, Dora Luz, Sterling Holloway
----------------------
Movie title: Make Mine Music
directors: Robert Cormack, Clyde Geronimi, Jack Kinney, Hamilton Luske, Joshua Meador
actors: Nelson Eddy, Dinah Shore, Benny Goodman, The Andrews Sisters
----------------------
Movie title: Song of the South
directors: Harve Foster, Wilfred Jackson
actors: Ruth Warrick, Bobby Driscoll, James Baskett, Luana Patten
----------------------
Movie title: Fun and Fancy Free
directors: Jack Kinney, Hamilton Luske, William Morgan, Bill Roberts
actors: Edgar Bergen, Dinah Shore, Luana Patten, Anita Gordon
----------------------
Movie title: So Dear to My Heart
directors: Harold D. Schuster, Hamilton Luske
actors: Burl Ives, Beulah Bondi, Bobby Driscoll, Luana Patten
----------------------
Movie title: Melody Time
directors: Clyde Geronimi, Wilfred Jackson, Jack Kinney, Hamilton Luske
actors: Roy Rogers, Trigger, Dennis Day, The Andrews Sisters
----------------------
Movie title: The Adventures of Ichabod and Mr. Toad
directors: James Algar, Clyde Geronimi, Jack Kinney
actors: Bing Crosby, Basil Rathbone, Eric Blore, John McLeish
----------------------
Movie title: Treasure Island
directors: Byron Haskin
actors: Bobby Driscoll, Robert Newton, Basil Sydney, Walter Fitzgerald
----------------------
Movie title: Cinderella
directors: Clyde Geronimi, Wilfred Jackson, Hamilton Luske
actors: Ilene Woods, James MacDonald, Eleanor Audley, Verna Felton
----------------------
Movie title: Alice in Wonderland
directors: Clyde Geronimi, Wilfred Jackson, Hamilton Luske
actors: Kathryn Beaumont, Ed Wynn, Richard Haydn, Sterling Holloway
----------------------
Movie title: The Story of Robin Hood and His Merrie Men
directors: Ken Annakin
actors: Richard Todd, Joan Rice, Peter Finch, James Hayter
----------------------
Movie title: Peter Pan
directors: Clyde Geronimi, Wilfred Jackson, Hamilton Luske, Jack Kinney
actors: Bobby Driscoll, Kathryn Beaumont, Hans Conried, Bill Thompson
----------------------
Movie title: Rob Roy: The Highland Rogue
directors: Harold French
actors: Richard Todd, Glynis Johns, James Robertson Justice, Michael Gough
----------------------
Movie title: The Sword and the Rose
directors: Ken Annakin
actors: Richard Todd, Glynis Johns, James Robertson Justice, Michael Gough
----------------------
Movie title: 20,000 Leagues Under the Sea
directors: Richard Fleischer
actors: Kirk Douglas, James Mason, Paul Lukas, Peter Lorre
----------------------
Movie title: Lady and the Tramp
directors: Clyde Geronimi, Wilfred Jackson, Hamilton Luske
actors: Barbara Luddy, Larry Roberts, Peggy Lee, Bill Thompson
----------------------
Movie title: The Littlest Outlaw
directors: Roberto Gavaldón
actors: Pedro Armendáriz, Joseph Calleia, Rodolfo Acosta, Andrés Velázquez
----------------------
Movie title: Davy Crockett: King of the Wild Frontier
directors: Norman Foster
actors: Fess Parker, Buddy Ebsen, Basil Ruysdael, Hans Conried
----------------------
Movie title: Westward Ho, the Wagons!
directors: William Beaudine
actors: Fess Parker, Kathleen Crowley, Jeff York, David Stollery
----------------------
Movie title: Davy Crockett and the River Pirates
directors: Norman Foster
actors: Fess Parker, Buddy Ebsen, Jeff York, Kenneth Tobey
----------------------
Movie title: The Great Locomotive Chase
directors: Francis D. Lyon
actors: Fess Parker, Jeffrey Hunter, Jeff York, John Lupton
----------------------
Movie title: Old Yeller
directors: Robert Stevenson
actors: Dorothy McGuire, Fess Parker, Tommy Kirk, Jeff York
----------------------
Movie title: Johnny Tremain
directors: Robert Stevenson
actors: Hal Stalmaster, Luana Patten, Jeff York, Sebastian Cabot
----------------------
Movie title: Tonka
directors: Lewis R. Foster
actors: Sal Mineo, Philip Carey, Jerome Courtland, H.M. Wynant
----------------------
Movie title: The Light in the Forest
directors: Herschel Daugherty
actors: Fess Parker, Wendell Corey, Joanne Dru, James MacArthur
----------------------
Movie title: The Shaggy Dog
directors: Charles Barton
actors: Fred MacMurray, Jean Hagen, Tommy Kirk, Annette Funicello
----------------------
Movie title: Sleeping Beauty
directors: Clyde Geronimi, Les Clark, Hamilton Luske, Wolfgang Reitherman
actors: Mary Costa, Bill Shirley, Eleanor Audley, Verna Felton
----------------------
Movie title: Third Man on the Mountain
directors: Ken Annakin
actors: Michael Rennie, James MacArthur, Janet Munro, James Donald
----------------------
Movie title: Darby O'Gill and the Little People
directors: Robert Stevenson
actors: Albert Sharpe, Janet Munro, Sean Connery, Jimmy O'Dea
----------------------
Movie title: Swiss Family Robinson
directors: Ken Annakin
actors: John Mills, Dorothy McGuire, James MacArthur, Janet Munro
----------------------
Movie title: Ten Who Dared
directors: William Beaudine
actors: Brian Keith, John Beal, James Drury, R.G. Armstrong
----------------------
Movie title: Kidnapped
directors: Robert Stevenson
actors: Peter Finch, James MacArthur, Bernard Lee, John Laurie
----------------------
Movie title: Toby Tyler or Ten Weeks with a Circus
directors: Charles Barton
actors: Kevin Corcoran, Henry Calvin, Gene Sheldon, Bob Sweeney
----------------------
Movie title: Pollyanna
directors: David Swift
actors: Jane Wyman, Hayley Mills, Richard Egan, Karl Malden
----------------------
Movie title: The Sign of Zorro
directors: Lewis R. Foster, Norman Foster
actors: Guy Williams, Henry Calvin, Gene Sheldon, Romney Brent
----------------------
Movie title: The Absent Minded Professor
directors: Robert Stevenson
actors: Fred MacMurray, Nancy Olson, Keenan Wynn, Tommy Kirk
----------------------
Movie title: Greyfriars Bobby: The True Story of a Dog
directors: Don Chaffey
actors: Donald Crisp, Laurence Naismith, Alex Mackenzie, Duncan Macrae
----------------------
Movie title: The Parent Trap
directors: David Swift
actors: Hayley Mills, Maureen O'Hara, Brian Keith, Charles Ruggles
----------------------
Movie title: Babes in Toyland
directors: Jack Donohue
actors: Ray Bolger, Tommy Sands, Annette Funicello, Ed Wynn
----------------------
Movie title: One Hundred and One Dalmatians
directors: Clyde Geronimi, Hamilton Luske, Wolfgang Reitherman
actors: Rod Taylor, Betty Lou Gerson, J. Pat O'Malley, Martha Wentworth
----------------------
Movie title: In Search of the Castaways
directors: Robert Stevenson
actors: Hayley Mills, Maurice Chevalier, George Sanders, Wilfrid Hyde-White
----------------------
Movie title: The Legend of Lobo
directors:
actors: Rex Allen, Ingvald Lieberkind
----------------------
Movie title: Almost Angels
directors: Steve Previn
actors: Vincent Winter, Sean Scully, Peter Weck, Hans Holt
----------------------
Movie title: Big Red
directors: Norman Tokar
actors: Walter Pidgeon, Gilles Payant, Émile Genest, Janette Bertrand
----------------------
Movie title: Moon Pilot
directors: James Neilson
actors: Tom Tryon, Brian Keith, Edmond O'Brien, Dany Saval
----------------------
Movie title: Bon Voyage!
directors: James Neilson
actors: Fred MacMurray, Jane Wyman, Michael Callan, Deborah Walley
----------------------
Movie title: Miracle of the White Stallions
directors: Arthur Hiller
actors: Robert Taylor, Lilli Palmer, Curd Jürgens, Eddie Albert
----------------------
Movie title: Summer Magic
directors: James Neilson
actors: Hayley Mills, Dorothy McGuire, Burl Ives, Deborah Walley
----------------------
Movie title: Savage Sam
directors: Norman Tokar
actors: Brian Keith, Tommy Kirk, Kevin Corcoran, Dewey Martin
----------------------
Movie title: The Incredible Journey
directors: Fletcher Markle
actors: Émile Genest, John Drainie, Tommy Tweed, Sandra Scott
----------------------
Movie title: The Sword in the Stone
directors: Wolfgang Reitherman, Clyde Geronimi, David Hand
actors: Rickie Sorensen, Sebastian Cabot, Karl Swenson, Junius Matthews
----------------------
Movie title: Son of Flubber
directors: Robert Stevenson
actors: Fred MacMurray, Nancy Olson, Keenan Wynn, Tommy Kirk
----------------------
Movie title: Mary Poppins
directors: Robert Stevenson
actors: Julie Andrews, Dick Van Dyke, David Tomlinson, Glynis Johns
----------------------
Movie title: A Tiger Walks
directors: Norman Tokar
actors: Brian Keith, Vera Miles, Pamela Franklin, Sabu
----------------------
Movie title: The Misadventures of Merlin Jones
directors: Robert Stevenson
actors: Tommy Kirk, Annette Funicello, Leon Ames, Stuart Erwin
----------------------
Movie title: The Three Lives of Thomasina
directors: Don Chaffey
actors: Patrick McGoohan, Susan Hampshire, Laurence Naismith, Jean Anderson
----------------------
Movie title: The Moon-Spinners
directors: James Neilson
actors: Hayley Mills, Eli Wallach, Pola Negri, Peter McEnery
----------------------
Movie title: Emil and the Detectives
directors: Peter Tewksbury
actors: Walter Slezak, Bryan Russell, Roger Mobley, Heinz Schubert
----------------------
Movie title: That Darn Cat!
directors: Robert Stevenson
actors: Hayley Mills, Dean Jones, Dorothy Provine, Roddy McDowall
----------------------
Movie title: The Monkey's Uncle
directors: Robert Stevenson
actors: Tommy Kirk, Annette Funicello, Leon Ames, Arthur O'Connell
----------------------
Movie title: Those Calloways

directors: Norman Tokar
actors: Brian Keith, Vera Miles, Brandon De Wilde, Walter Brennan
----------------------
Movie title: The Ugly Dachshund
directors: Norman Tokar
actors: Dean Jones, Suzanne Pleshette, Charles Ruggles, Kelly Thordsen
----------------------
Movie title: Follow Me, Boys!
directors: Norman Tokar
actors: Fred MacMurray, Vera Miles, Lillian Gish, Charles Ruggles
----------------------
Movie title: The Fighting Prince of Donegal
directors: Michael O'Herlihy
actors: Peter McEnery, Susan Hampshire, Tom Adams, Gordon Jackson
----------------------
Movie title: Lt. Robin Crusoe, U.S.N.
directors: Byron Paul
actors: Dick Van Dyke, Nancy Kwan, Akim Tamiroff, Arthur Malet
----------------------
Movie title: The Jungle Book
directors: Wolfgang Reitherman, James Algar, Jack Kinney
actors: Phil Harris, Sebastian Cabot, Louis Prima, Bruce Reitherman
----------------------
Movie title: The Happiest Millionaire
directors: Norman Tokar
actors: Fred MacMurray, Tommy Steele, Greer Garson, Gladys Cooper
----------------------
Movie title: Charlie, the Lonesome Cougar
directors: Winston Hibler
actors: Ron Brown, Brian Russell, Linda Wallace, Jim Wilson
----------------------
Movie title: The Gnome-Mobile
directors: Robert Stevenson
actors: Walter Brennan, Matthew Garber, Karen Dotrice, Richard Deacon
----------------------
Movie title: The Adventures of Bullwhip Griffin
directors: James Neilson
actors: Roddy McDowall, Suzanne Pleshette, Karl Malden, Harry Guardino
----------------------
Movie title: Monkeys, Go Home!
directors: Andrew V. McLaglen
actors: Maurice Chevalier, Dean Jones, Yvette Mimieux, Bernard Woringer
----------------------
Movie title: Never a Dull Moment
directors: Jerry Paris
actors: Dick Van Dyke, Edward G. Robinson, Dorothy Provine, Henry Silva
----------------------
Movie title: Blackbeard's Ghost
directors: Robert Stevenson
actors: Peter Ustinov, Dean Jones, Suzanne Pleshette, Elsa Lanchester
----------------------
Movie title: The Love Bug
directors: Robert Stevenson
actors: Dean Jones, Michele Lee, David Tomlinson, Buddy Hackett
----------------------
Movie title: The One and Only, Genuine, Original Family Band
directors: Michael O'Herlihy
actors: Walter Brennan, Buddy Ebsen, Lesley Ann Warren, John Davidson
----------------------
Movie title: The Horse in the Gray Flannel Suit
directors: Norman Tokar
actors: Dean Jones, Diane Baker, Lloyd Bochner, Fred Clark
----------------------
Movie title: The Horse in the Gray Flannel Suit
directors: Norman Tokar
actors: Dean Jones, Diane Baker, Lloyd Bochner, Fred Clark
----------------------
Movie title: The Computer Wore Tennis Shoes
directors: Robert Butler
actors: Kurt Russell, Cesar Romero, Joe Flynn, William Schallert
----------------------
Movie title: Rascal
directors: Norman Tokar
actors: Steve Forrest, Bill Mumy, Pamela Toll, Elsa Lanchester
----------------------
Movie title: Smith!
directors: Michael O'Herlihy
actors: Glenn Ford, Nancy Olson, Dean Jagger, Keenan Wynn
----------------------
Movie title: Smoke
directors: Vincent McEveety
actors: Earl Holliman, Ron Howard, Jacqueline Scott, Shug Fisher
----------------------
Movie title: The Aristocats
directors: Wolfgang Reitherman
actors: Phil Harris, Eva Gabor, Sterling Holloway, Scatman Crothers
----------------------
Movie title: The Wild Country
directors: Robert Totten
actors: Steve Forrest, Vera Miles, Ron Howard, Clint Howard
----------------------
Movie title: King of the Grizzlies
directors: Ron Kelly
actors: John Yesno, Chris Wiggins, Hugh Webster, Jack Van Evera
----------------------
Movie title: The Boatniks
directors: Norman Tokar
actors: Robert Morse, Stefanie Powers, Phil Silvers, Norman Fell
----------------------
Movie title: The Million Dollar Duck
directors: Vincent McEveety
actors: Dean Jones, Sandy Duncan, Joe Flynn, Tony Roberts
----------------------
Movie title: Bedknobs and Broomsticks
directors: Robert Stevenson, Ward Kimball
actors: Angela Lansbury, David Tomlinson, Roddy McDowall, Sam Jaffe
----------------------
Movie title: Scandalous John
directors: Robert Butler
actors: Brian Keith, Alfonso Arau, Michele Carey, Rick Lenz
----------------------
Movie title: The Barefoot Executive
directors: Robert Butler
actors: Kurt Russell, Joe Flynn, Harry Morgan, Wally Cox
----------------------
Movie title: Chandar, the Black Leopard of Ceylon
directors: Winston Hibler
actors: Ben Wright, Joe Abeywickrama, Esrom Jayasinghe, Frederick Steyne
----------------------
Movie title: Run, Cougar, Run
directors: Jerome Courtland
actors: Stuart Whitman, Frank Aletter, Lonny Chapman, Douglas Fowley
----------------------
Movie title: Napoleon and Samantha
directors: Bernard McEveety
actors: Michael Douglas, Jodie Foster, Johnny Whitaker, Will Geer

C:\Users\USER\anaconda3\lib\site-packages\splinter\driver\webdriver\__init__.py:528: FutureWarning: browser.find_link_by_partial_text is deprecated. Use browser.links.find_by_partial_text instead.
  FutureWarning,

----------------------
Movie title: Snow White and the Seven Dwarfs
directors: William Cottrell, David Hand, Wilfred Jackson, Larry Morey, Perce Pearce, Ben Sharpsteen
actors: Adriana Caselotti, Harry Stockwell, Lucille La Verne, Roy Atwell
----------------------
Movie title: Pinocchio
directors: Norman Ferguson, T. Hee, Wilfred Jackson, Jack Kinney, Hamilton Luske, Bill Roberts, Ben Sharpsteen
actors: Dickie Jones, Christian Rub, Mel Blanc, Don Brodie
----------------------
Movie title: Fantasia
directors: James Algar, Samuel Armstrong, Ford Beebe Jr., Norman Ferguson, David Hand, Jim Handley, T. Hee, Wilfred Jackson, Hamilton Luske, Bill Roberts, Paul Satterfield, Ben Sharpsteen
actors: Leopold Stokowski, Deems Taylor, The Philadelphia Orchestra, Corey Burton
----------------------
Movie title: The Reluctant Dragon
directors: Alfred L. Werker, Hamilton Luske, Jack Cutting, Ub Iwerks, Jack Kinney
actors: Robert Benchley, Frances Gifford, Buddy Pepper, Nana Bryant
----------------------
Movie title: Dumbo
directors: Samuel Armstrong, Norman Ferguson, Wilfred Jackson, Jack Kinney, Bill Roberts, Ben Sharpsteen, John Elliotte
actors: Sterling Holloway, Edward Brophy, Herman Bing, Billy Bletcher
----------------------
Movie title: Bambi
directors: James Algar, Samuel Armstrong, David Hand, Graham Heid, Bill Roberts, Paul Satterfield, Norman Wright, Arthur Davis, Clyde Geronimi
actors: Hardie Albright, Stan Alexander, Bobette Audrey, Peter Behn
----------------------
Movie title: Saludos Amigos
directors: Wilfred Jackson, Jack Kinney, Hamilton Luske, Bill Roberts, Norman Ferguson
actors: Fred Shields, José Oliveira, Lee Blair, Mary Blair
----------------------
Movie title: Victory Through Air Power
directors: James Algar, Clyde Geronimi, Jack Kinney, H.C. Potter
actors: Alexander de Seversky, Art Baker, Billy Mitchell
----------------------
Movie title: The Three Caballeros
directors: Norman Ferguson, Clyde Geronimi, Jack Kinney, Bill Roberts, Harold Young
actors: Aurora Miranda, Carmen Molina, Dora Luz, Sterling Holloway
----------------------
Movie title: Make Mine Music
directors: Robert Cormack, Clyde Geronimi, Jack Kinney, Hamilton Luske, Joshua Meador
actors: Nelson Eddy, Dinah Shore, Benny Goodman, The Andrews Sisters
----------------------
Movie title: Song of the South
directors: Harve Foster, Wilfred Jackson
actors: Ruth Warrick, Bobby Driscoll, James Baskett, Luana Patten
----------------------
Movie title: Fun and Fancy Free
directors: Jack Kinney, Hamilton Luske, William Morgan, Bill Roberts
actors: Edgar Bergen, Dinah Shore, Luana Patten, Anita Gordon
----------------------
Movie title: So Dear to My Heart
directors: Harold D. Schuster, Hamilton Luske
actors: Burl Ives, Beulah Bondi, Bobby Driscoll, Luana Patten
----------------------
Movie title: Melody Time
directors: Clyde Geronimi, Wilfred Jackson, Jack Kinney, Hamilton Luske
actors: Roy Rogers, Trigger, Dennis Day, The Andrews Sisters
----------------------
Movie title: The Adventures of Ichabod and Mr. Toad
directors: James Algar, Clyde Geronimi, Jack Kinney
actors: Bing Crosby, Basil Rathbone, Eric Blore, John McLeish
----------------------
Movie title: Treasure Island
directors: Byron Haskin
actors: Bobby Driscoll, Robert Newton, Basil Sydney, Walter Fitzgerald
----------------------
Movie title: Cinderella
directors: Clyde Geronimi, Wilfred Jackson, Hamilton Luske
actors: Ilene Woods, James MacDonald, Eleanor Audley, Verna Felton
----------------------
Movie title: Alice in Wonderland
directors: Clyde Geronimi, Wilfred Jackson, Hamilton Luske
actors: Kathryn Beaumont, Ed Wynn, Richard Haydn, Sterling Holloway
----------------------
Movie title: The Story of Robin Hood and His Merrie Men
directors: Ken Annakin
actors: Richard Todd, Joan Rice, Peter Finch, James Hayter
----------------------
Movie title: Peter Pan
directors: Clyde Geronimi, Wilfred Jackson, Hamilton Luske, Jack Kinney
actors: Bobby Driscoll, Kathryn Beaumont, Hans Conried, Bill Thompson
----------------------
Movie title: Rob Roy: The Highland Rogue
directors: Harold French
actors: Richard Todd, Glynis Johns, James Robertson Justice, Michael Gough
----------------------
Movie title: The Sword and the Rose
directors: Ken Annakin
actors: Richard Todd, Glynis Johns, James Robertson Justice, Michael Gough
----------------------
Movie title: 20,000 Leagues Under the Sea
directors: Richard Fleischer
actors: Kirk Douglas, James Mason, Paul Lukas, Peter Lorre
----------------------
Movie title: Lady and the Tramp
directors: Clyde Geronimi, Wilfred Jackson, Hamilton Luske
actors: Barbara Luddy, Larry Roberts, Peggy Lee, Bill Thompson
----------------------
Movie title: The Littlest Outlaw
directors: Roberto Gavaldón
actors: Pedro Armendáriz, Joseph Calleia, Rodolfo Acosta, Andrés Velázquez
----------------------
Movie title: Davy Crockett: King of the Wild Frontier
directors: Norman Foster
actors: Fess Parker, Buddy Ebsen, Basil Ruysdael, Hans Conried
----------------------
Movie title: Westward Ho, the Wagons!
directors: William Beaudine
actors: Fess Parker, Kathleen Crowley, Jeff York, David Stollery
----------------------
Movie title: Davy Crockett and the River Pirates
directors: Norman Foster
actors: Fess Parker, Buddy Ebsen, Jeff York, Kenneth Tobey
----------------------
Movie title: The Great Locomotive Chase
directors: Francis D. Lyon
actors: Fess Parker, Jeffrey Hunter, Jeff York, John Lupton
----------------------
Movie title: Old Yeller
directors: Robert Stevenson
actors: Dorothy McGuire, Fess Parker, Tommy Kirk, Jeff York
----------------------
Movie title: Johnny Tremain
directors: Robert Stevenson
actors: Hal Stalmaster, Luana Patten, Jeff York, Sebastian Cabot
----------------------
Movie title: Tonka
directors: Lewis R. Foster
actors: Sal Mineo, Philip Carey, Jerome Courtland, H.M. Wynant
----------------------
Movie title: The Light in the Forest
directors: Herschel Daugherty
actors: Fess Parker, Wendell Corey, Joanne Dru, James MacArthur
----------------------
Movie title: The Shaggy Dog
directors: Charles Barton
actors: Fred MacMurray, Jean Hagen, Tommy Kirk, Annette Funicello
----------------------
Movie title: Sleeping Beauty
directors: Clyde Geronimi, Les Clark, Hamilton Luske, Wolfgang Reitherman
actors: Mary Costa, Bill Shirley, Eleanor Audley, Verna Felton
----------------------
Movie title: Third Man on the Mountain
directors: Ken Annakin
actors: Michael Rennie, James MacArthur, Janet Munro, James Donald
----------------------
Movie title: Darby O'Gill and the Little People
directors: Robert Stevenson
actors: Albert Sharpe, Janet Munro, Sean Connery, Jimmy O'Dea
----------------------
Movie title: Swiss Family Robinson
directors: Ken Annakin
actors: John Mills, Dorothy McGuire, James MacArthur, Janet Munro
----------------------
Movie title: Ten Who Dared
directors: William Beaudine
actors: Brian Keith, John Beal, James Drury, R.G. Armstrong
----------------------
Movie title: Kidnapped
directors: Robert Stevenson
actors: Peter Finch, James MacArthur, Bernard Lee, John Laurie
----------------------
Movie title: Toby Tyler or Ten Weeks with a Circus
directors: Charles Barton
actors: Kevin Corcoran, Henry Calvin, Gene Sheldon, Bob Sweeney
----------------------
Movie title: Pollyanna
directors: David Swift
actors: Jane Wyman, Hayley Mills, Richard Egan, Karl Malden
----------------------
Movie title: The Sign of Zorro
directors: Lewis R. Foster, Norman Foster
actors: Guy Williams, Henry Calvin, Gene Sheldon, Romney Brent
----------------------
Movie title: The Absent Minded Professor
directors: Robert Stevenson
actors: Fred MacMurray, Nancy Olson, Keenan Wynn, Tommy Kirk
----------------------
Movie title: Greyfriars Bobby: The True Story of a Dog
directors: Don Chaffey
actors: Donald Crisp, Laurence Naismith, Alex Mackenzie, Duncan Macrae
----------------------
Movie title: The Parent Trap
directors: David Swift
actors: Hayley Mills, Maureen O'Hara, Brian Keith, Charles Ruggles
----------------------
Movie title: Babes in Toyland
directors: Jack Donohue
actors: Ray Bolger, Tommy Sands, Annette Funicello, Ed Wynn
----------------------
Movie title: One Hundred and One Dalmatians
directors: Clyde Geronimi, Hamilton Luske, Wolfgang Reitherman
actors: Rod Taylor, Betty Lou Gerson, J. Pat O'Malley, Martha Wentworth
----------------------
Movie title: In Search of the Castaways
directors: Robert Stevenson
actors: Hayley Mills, Maurice Chevalier, George Sanders, Wilfrid Hyde-White
----------------------
Movie title: The Legend of Lobo
directors:
actors: Rex Allen, Ingvald Lieberkind
----------------------
Movie title: Almost Angels
directors: Steve Previn
actors: Vincent Winter, Sean Scully, Peter Weck, Hans Holt
----------------------
Movie title: Big Red
directors: Norman Tokar
actors: Walter Pidgeon, Gilles Payant, Émile Genest, Janette Bertrand
----------------------
Movie title: Moon Pilot
directors: James Neilson
actors: Tom Tryon, Brian Keith, Edmond O'Brien, Dany Saval
----------------------
Movie title: Bon Voyage!
directors: James Neilson
actors: Fred MacMurray, Jane Wyman, Michael Callan, Deborah Walley
----------------------
Movie title: Miracle of the White Stallions
directors: Arthur Hiller
actors: Robert Taylor, Lilli Palmer, Curd Jürgens, Eddie Albert
----------------------

Movie title: Summer Magic
directors: James Neilson
actors: Hayley Mills, Dorothy McGuire, Burl Ives, Deborah Walley
----------------------
Movie title: Savage Sam
directors: Norman Tokar
actors: Brian Keith, Tommy Kirk, Kevin Corcoran, Dewey Martin
----------------------
Movie title: The Incredible Journey
directors: Fletcher Markle
actors: Émile Genest, John Drainie, Tommy Tweed, Sandra Scott
----------------------
Movie title: The Sword in the Stone
directors: Wolfgang Reitherman, Clyde Geronimi, David Hand
actors: Rickie Sorensen, Sebastian Cabot, Karl Swenson, Junius Matthews
----------------------
Movie title: Son of Flubber
directors: Robert Stevenson
actors: Fred MacMurray, Nancy Olson, Keenan Wynn, Tommy Kirk
----------------------
Movie title: Mary Poppins
directors: Robert Stevenson
actors: Julie Andrews, Dick Van Dyke, David Tomlinson, Glynis Johns
----------------------
Movie title: A Tiger Walks
directors: Norman Tokar
actors: Brian Keith, Vera Miles, Pamela Franklin, Sabu
----------------------
Movie title: The Misadventures of Merlin Jones
directors: Robert Stevenson
actors: Tommy Kirk, Annette Funicello, Leon Ames, Stuart Erwin
----------------------
Movie title: The Three Lives of Thomasina
directors: Don Chaffey
actors: Patrick McGoohan, Susan Hampshire, Laurence Naismith, Jean Anderson
----------------------
Movie title: The Moon-Spinners
directors: James Neilson
actors: Hayley Mills, Eli Wallach, Pola Negri, Peter McEnery
----------------------
Movie title: Emil and the Detectives
directors: Peter Tewksbury
actors: Walter Slezak, Bryan Russell, Roger Mobley, Heinz Schubert
----------------------
Movie title: That Darn Cat!
directors: Robert Stevenson
actors: Hayley Mills, Dean Jones, Dorothy Provine, Roddy McDowall
----------------------
Movie title: The Monkey's Uncle
directors: Robert Stevenson
actors: Tommy Kirk, Annette Funicello, Leon Ames, Arthur O'Connell
----------------------
Movie title: Those Calloways
directors: Norman Tokar
actors: Brian Keith, Vera Miles, Brandon De Wilde, Walter Brennan
----------------------
Movie title: The Ugly Dachshund
directors: Norman Tokar
actors: Dean Jones, Suzanne Pleshette, Charles Ruggles, Kelly Thordsen
----------------------
Movie title: Follow Me, Boys!
directors: Norman Tokar
actors: Fred MacMurray, Vera Miles, Lillian Gish, Charles Ruggles
----------------------
Movie title: The Fighting Prince of Donegal
directors: Michael O'Herlihy
actors: Peter McEnery, Susan Hampshire, Tom Adams, Gordon Jackson
----------------------
Movie title: Lt. Robin Crusoe, U.S.N.
directors: Byron Paul
actors: Dick Van Dyke, Nancy Kwan, Akim Tamiroff, Arthur Malet
----------------------
Movie title: The Jungle Book
directors: Wolfgang Reitherman, James Algar, Jack Kinney
actors: Phil Harris, Sebastian Cabot, Louis Prima, Bruce Reitherman
----------------------
Movie title: The Happiest Millionaire
directors: Norman Tokar
actors: Fred MacMurray, Tommy Steele, Greer Garson, Gladys Cooper
----------------------
Movie title: Charlie, the Lonesome Cougar
directors: Winston Hibler
actors: Ron Brown, Brian Russell, Linda Wallace, Jim Wilson
----------------------
Movie title: The Gnome-Mobile
directors: Robert Stevenson
actors: Walter Brennan, Matthew Garber, Karen Dotrice, Richard Deacon
----------------------
Movie title: The Adventures of Bullwhip Griffin
directors: James Neilson
actors: Roddy McDowall, Suzanne Pleshette, Karl Malden, Harry Guardino
----------------------
Movie title: Monkeys, Go Home!
directors: Andrew V. McLaglen
actors: Maurice Chevalier, Dean Jones, Yvette Mimieux, Bernard Woringer
----------------------
Movie title: Never a Dull Moment
directors: Jerry Paris
actors: Dick Van Dyke, Edward G. Robinson, Dorothy Provine, Henry Silva
----------------------
Movie title: Blackbeard's Ghost
directors: Robert Stevenson
actors: Peter Ustinov, Dean Jones, Suzanne Pleshette, Elsa Lanchester
----------------------
Movie title: The Love Bug
directors: Robert Stevenson
actors: Dean Jones, Michele Lee, David Tomlinson, Buddy Hackett
----------------------
Movie title: The One and Only, Genuine, Original Family Band
directors: Michael O'Herlihy
actors: Walter Brennan, Buddy Ebsen, Lesley Ann Warren, John Davidson
----------------------
Movie title: The Horse in the Gray Flannel Suit
directors: Norman Tokar
actors: Dean Jones, Diane Baker, Lloyd Bochner, Fred Clark
----------------------
Movie title: The Horse in the Gray Flannel Suit
directors: Norman Tokar
actors: Dean Jones, Diane Baker, Lloyd Bochner, Fred Clark
----------------------
Movie title: The Computer Wore Tennis Shoes
directors: Robert Butler
actors: Kurt Russell, Cesar Romero, Joe Flynn, William Schallert
----------------------
Movie title: Rascal
directors: Norman Tokar
actors: Steve Forrest, Bill Mumy, Pamela Toll, Elsa Lanchester
----------------------
Movie title: Smith!
directors: Michael O'Herlihy
actors: Glenn Ford, Nancy Olson, Dean Jagger, Keenan Wynn
----------------------
Movie title: Smoke
directors: Vincent McEveety
actors: Earl Holliman, Ron Howard, Jacqueline Scott, Shug Fisher
----------------------
Movie title: The Aristocats
directors: Wolfgang Reitherman
actors: Phil Harris, Eva Gabor, Sterling Holloway, Scatman Crothers
----------------------
Movie title: The Wild Country
directors: Robert Totten
actors: Steve Forrest, Vera Miles, Ron Howard, Clint Howard
----------------------
Movie title: King of the Grizzlies
directors: Ron Kelly
actors: John Yesno, Chris Wiggins, Hugh Webster, Jack Van Evera
----------------------
Movie title: The Boatniks
directors: Norman Tokar
actors: Robert Morse, Stefanie Powers, Phil Silvers, Norman Fell
----------------------
Movie title: The Million Dollar Duck
directors: Vincent McEveety
actors: Dean Jones, Sandy Duncan, Joe Flynn, Tony Roberts
----------------------
Movie title: Bedknobs and Broomsticks
directors: Robert Stevenson, Ward Kimball
actors: Angela Lansbury, David Tomlinson, Roddy McDowall, Sam Jaffe
----------------------
Movie title: Scandalous John
directors: Robert Butler
actors: Brian Keith, Alfonso Arau, Michele Carey, Rick Lenz
----------------------
Movie title: The Barefoot Executive
directors: Robert Butler
actors: Kurt Russell, Joe Flynn, Harry Morgan, Wally Cox
----------------------
Movie title: Chandar, the Black Leopard of Ceylon
directors: Winston Hibler
actors: Ben Wright, Joe Abeywickrama, Esrom Jayasinghe, Frederick Steyne
----------------------
Movie title: Run, Cougar, Run
directors: Jerome Courtland
actors: Stuart Whitman, Frank Aletter, Lonny Chapman, Douglas Fowley
----------------------
Movie title: Napoleon and Samantha
directors: Bernard McEveety
actors: Michael Douglas, Jodie Foster, Johnny Whitaker, Will Geer
----------------------
Movie title: Snowball Express
directors: Norman Tokar
actors: Dean Jones, Nancy Olson, Harry Morgan, Keenan Wynn
----------------------
Movie title: The Biscuit Eater
directors: Vincent McEveety
actors: Earl Holliman, Pat Crowley, Lew Ayres, Godfrey Cambridge
----------------------
Movie title: Now You See Him, Now You Don't
directors: Robert Butler
actors: Kurt Russell, Cesar Romero, Joe Flynn, Jim Backus
----------------------
Movie title: The World's Greatest Athlete
directors: Robert Scheerer
actors: John Amos, Jan-Michael Vincent, Tim Conway, Roscoe Lee Browne
----------------------
Movie title: Charley and the Angel
directors: Vincent McEveety
actors: Fred MacMurray, Cloris Leachman, Harry Morgan, Kurt Russell
----------------------
Movie title: One Little Indian
directors: Bernard McEveety
actors: James Garner, Vera Miles, Pat Hingle, Morgan Woodward
----------------------
Movie title: Mustang
directors: Roy Edward Disney, Frank Zuniga
actors: Charles Baca, Flavio Martinez, Ignacio Ramírez, Eloy Casados
----------------------
Movie title: Superdad
directors: Vincent McEveety
actors: Bob Crane, Kurt Russell, Barbara Rush, Joe Flynn
----------------------
Movie title: Robin Hood
directors: Wolfgang Reitherman, David Hand
actors: Brian Bedford, Phil Harris, Roger Miller, Peter Ustinov
----------------------
Movie title: The Island at the Top of the World
directors: Robert Stevenson
actors: David Hartman, Donald Sinden, Jacques Marin, Mako
----------------------
Movie title: The Castaway Cowboy
directors: Vincent McEveety
actors: James Garner, Vera Miles, Robert Culp, Eric Shea
----------------------
Movie title: The Bears and I
directors: Bernard McEveety
actors: Patrick Wayne, Chief Dan George, Andrew Duggan, Michael Ansara
----------------------
Movie title: Herbie Rides Again
directors: Robert Stevenson
actors: Helen Hayes, Ken Berry, Stefanie Powers, John McIntire
----------------------
Movie title: Ride a Wild Pony
directors: Don Chaffey
actors: Michael Craig, John Meillon, Robert Bettles, Eva Griffith
----------------------
Movie title: The Boy Who Talked to Badgers
directors: Gary Nelson
actors: Christian Juttner, Carl Betz, Salome Jens, Denver Pyle
----------------------
Movie title: One of Our Dinosaurs Is Missing
directors: Robert Stevenson
actors: Peter Ustinov, Helen Hayes, Derek Nimmo, Hugh Burden
----------------------
Movie title: One of Our Dinosaurs Is Missing
directors: Robert Stevenson
actors: Peter Ustinov, Helen Hayes, Derek Nimmo, Hugh Burden
----------------------
Movie title: Escape to Witch Mountain
directors: John Hough
actors: Eddie Albert, Ray Milland, Donald Pleasence, Kim Richards
----------------------
Movie title: The Apple Dumpling Gang
directors: Norman Tokar
actors: Bill Bixby, Susan Clark, Don Knotts, Tim Conway
----------------------
Movie title: The Strongest Man in the World
directors: Vincent McEveety
actors: Kurt Russell, Joe Flynn, Eve Arden, Cesar Romero
----------------------
Movie title: The Shaggy D.A.
directors: Robert Stevenson
actors: Dean Jones, Suzanne Pleshette, Tim Conway, Keenan Wynn
----------------------
Movie title: Treasure of Matecumbe
directors: Vincent McEveety
actors: Robert Foxworth, Joan Hackett, Peter Ustinov, Vic Morrow
----------------------
Movie title: No Deposit, No Return
directors: Norman Tokar
actors: David Niven, Darren McGavin, Don Knotts, Herschel Bernardi
----------------------
Movie title: Freaky Friday
directors: Gary Nelson
actors: Barbara Harris, Jodie Foster, John Astin, Patsy Kelly
----------------------
Movie title: Gus
directors: Vincent McEveety
actors: Edward Asner, Don Knotts, Gary Grimes, Tim Conway
----------------------
Movie title: The Littlest Horse Thieves
directors: Charles Jarrott
actors: Alastair Sim, Peter Barkworth, Maurice Colbourne, Susan Tebbs
----------------------
Movie title: Candleshoe
directors: Norman Tokar
actors: Jodie Foster, David Niven, Helen Hayes, Leo McKern
----------------------
Movie title: The Rescuers
directors: John Lounsbery, Wolfgang Reitherman, Art Stevens
actors: Bob Newhart, Eva Gabor, Geraldine Page, Joe Flynn
----------------------
Movie title: A Tale of Two Critters
directors: Jack Speirs
actors: Mayf Nutter
----------------------
Movie title: The Many Adventures of Winnie the Pooh
directors: John Lounsbery, Wolfgang Reitherman, Ben Sharpsteen
actors: Sebastian Cabot, Junius Matthews, Barbara Luddy, Howard Morris
----------------------
Movie title: Herbie Goes to Monte Carlo
directors: Vincent McEveety
actors: Dean Jones, Don Knotts, Julie Sommars, Jacques Marin
----------------------
Movie title: Pete's Dragon
directors: Don Chaffey, Don Bluth
actors: Sean Marshall, Helen Reddy, Jim Dale, Mickey Rooney
----------------------
Movie title: Hot Lead and Cold Feet
directors: Robert Butler
actors: Jim Dale, Darren McGavin, Karen Valentine, Don Knotts
----------------------
Movie title: Return from Witch Mountain
directors: John Hough
actors: Bette Davis, Christopher Lee, Kim Richards, Ike Eisenmann
----------------------
Movie title: The Cat from Outer Space
directors: Norman Tokar
actors: Ken Berry, Sandy Duncan, Harry Morgan, Roddy McDowall
----------------------
Movie title: The Black Hole
directors: Gary Nelson
actors: Maximilian Schell, Anthony Perkins, Robert Forster, Joseph Bottoms
----------------------
Movie title: The Muppet Movie
directors: James Frawley
actors: Jim Henson, Frank Oz, Jerry Nelson, Richard Hunt
----------------------
Movie title: Unidentified Flying Oddball
directors: Russ Mayberry
actors: Dennis Dugan, Jim Dale, Ron Moody, Kenneth More
----------------------
Movie title: The North Avenue Irregulars
directors: Bruce Bilson
actors: Edward Herrmann, Barbara Harris, Susan Clark, Karen Valentine
----------------------
Movie title: The Apple Dumpling Gang Rides Again
directors: Vincent McEveety
actors: Tim Conway, Don Knotts, Tim Matheson, Kenneth Mars
----------------------
Movie title: The Last Flight of Noah's Ark
directors: Charles Jarrott
actors: Elliott Gould, Geneviève Bujold, Ricky Schroder, Vincent Gardenia
----------------------
Movie title: The Watcher in the Woods
directors: John Hough, Vincent McEveety
actors: Bette Davis, Lynn-Holly Johnson, Kyle Richards, Carroll Baker
----------------------
Movie title: Midnight Madness
directors: Michael Nankin, David Wechter
actors: David Naughton, Debra Clinger, Joel Kenney, David Damas
----------------------
Movie title: Popeye
directors: Robert Altman
actors: Robin Williams, Shelley Duvall, Ray Walston, Paul Dooley
----------------------
Movie title: Herbie Goes Bananas
directors: Vincent McEveety
actors: Charles Martin Smith, Stephen W. Burns, Cloris Leachman, John Vernon
----------------------
Movie title: Dragonslayer
directors: Matthew Robbins
actors: Peter MacNicol, Caitlin Clarke, Ralph Richardson, John Hallam
----------------------
Movie title: Amy
directors: Vincent McEveety
actors: Jenny Agutter, Barry Newman, Kathleen Nolan, Chris Robinson
----------------------
Movie title: The Devil and Max Devlin
directors: Steven Hilliard Stern
actors: Elliott Gould, Bill Cosby, Susan Anspach, Adam Rich
----------------------
Movie title: Condorman
directors: Charles Jarrott
actors: Michael Crawford, Oliver Reed, Barbara Carrera, James Hampton
----------------------
Movie title: The Fox and the Hound
directors: Ted Berman, Richard Rich, Art Stevens, David Hand, Wolfgang Reitherman
actors: Mickey Rooney, Kurt Russell, Pearl Bailey, Jack Albertson
----------------------
Movie title: Tex
directors: Tim Hunter
actors: Matt Dillon, Jim Metzler, Meg Tilly, Bill McKinney
----------------------
Movie title: Night Crossing
directors: Delbert Mann
actors: John Hurt, Jane Alexander, Doug McKeon, Keith McKeon
----------------------
Movie title: TRON
directors: Steven Lisberger
actors: Jeff Bridges, Bruce Boxleitner, David Warner, Cindy Morgan
----------------------
Movie title: Tiger Town
directors: Alan Shapiro
actors: Bethany Carpenter, Lindsay Barr, Dave Bokas, Chris Bremer
----------------------
Movie title: Something Wicked This Way Comes
directors: Jack Clayton
actors: Jason Robards, Jonathan Pryce, Diane Ladd, Royal Dano
----------------------
Movie title: Trenchcoat
directors: Michael Tuchner
actors: Margot Kidder, Robert Hays, David Suchet, Gila von Weitershausen
----------------------
Movie title: Never Cry Wolf
directors: Carroll Ballard
actors: Charles Martin Smith, Brian Dennehy, Zachary Ittimangnaq, Samson Jorah
----------------------
Movie title: Love Leads the Way: A True Story
directors: Delbert Mann
actors: Timothy Bottoms, Eva Marie Saint, Arthur Hill, Glynnis O'Connor
----------------------
Movie title: Where the Toys Come from

directors: Theodore Thomas
actors: Sab Shimono, Erin Young, Jon Harvey, Larry Wright
----------------------
Movie title: Return to Oz
directors: Walter Murch
actors: Fairuza Balk, Nicol Williamson, Jean Marsh, Piper Laurie
----------------------
Movie title: The Black Cauldron
directors: Ted Berman, Richard Rich
actors: Grant Bardsley, Freddie Jones, Susan Sheridan, Nigel Hawthorne
----------------------
Movie title: The Journey of Natty Gann
directors: Jeremy Kagan
actors: Meredith Salenger, John Cusack, Ray Wise, Lainie Kazan
----------------------
Movie title: One Magic Christmas
directors: Phillip Borsos
actors: Mary Steenburgen, Gary Basaraba, Harry Dean Stanton, Arthur Hill
----------------------
Movie title:  The Magical World of Disney
directors: Corey Allen
actors: Scott Bakula, Ellen Bry, Joey Cramer, John Bloom
----------------------
Movie title: The Great Mouse Detective
directors: Ron Clements, Burny Mattinson, David Michener, John Musker
actors: Vincent Price, Barrie Ingham, Val Bettin, Susanne Pollatschek
----------------------
Movie title: Flight of the Navigator
directors: Randal Kleiser
actors: Joey Cramer, Paul Reubens, Cliff De Young, Veronica Cartwright
----------------------
Movie title: The Parent Trap II
directors: Ron Maxwell
actors: Hayley Mills, Tom Skerritt, Carrie Kei Heim, Bridgette Andersen
----------------------
Movie title: Benji the Hunted
directors: Joe Camp
actors: Red Steagall, Frank Inn, Benji, Nancy Francis
----------------------
Movie title: The Brave Little Toaster
directors: Jerry Rees
actors: Jon Lovitz, Timothy Stack, Timothy E. Day, Thurl Ravenscroft
----------------------
Movie title: Oliver & Company
directors: George Scribner
actors: Joey Lawrence, Billy Joel, Cheech Marin, Richard Mulligan
----------------------
Movie title: Return to Snowy River
directors: Geoff Burrowes
actors: Tom Burlinson, Sigrid Thornton, Brian Dennehy, Nicholas Eadie
----------------------
Movie title: Cheetah
directors: Jeff Blyth
actors: Keith Coogan, Lucy Deakins, Colin Mothupi, Timothy Landfield
----------------------
Movie title: The Little Mermaid
directors: Ron Clements, John Musker
actors: Jodi Benson, Samuel E. Wright, Rene Auberjonois, Christopher Daniel Barnes
----------------------
Movie title: Honey, I Shrunk the Kids
directors: Joe Johnston
actors: Rick Moranis, Matt Frewer, Marcia Strassman, Kristine Sutherland
----------------------
Movie title: The Rescuers Down Under
directors: Hendel Butoy, Mike Gabriel
actors: Bob Newhart, Eva Gabor, John Candy, Tristan Rogers
----------------------
Movie title: Shipwrecked
directors: Nils Gaup
actors: Stian Smestad, Gabriel Byrne, Louisa Milwood-Haigh, Trond Peter Stamsø Munch
----------------------
Movie title: DuckTales the Movie: Treasure of the Lost Lamp
directors: Bob Hathcock
actors: Alan Young, Christopher Lloyd, Terence McGovern, Russi Taylor
----------------------
Movie title: White Fang
directors: Randal Kleiser
actors: Ethan Hawke, Klaus Maria Brandauer, Jed, Seymour Cassel
----------------------
Movie title: Wild Hearts Can't Be Broken
directors: Steve Miner
actors: Gabrielle Anwar, Michael Schoeffling, Cliff Robertson, Dylan Kussman
----------------------
Movie title: Beauty and the Beast
directors: Gary Trousdale, Kirk Wise
actors: Paige O'Hara, Robby Benson, Jesse Corti, Rex Everhart
----------------------
Movie title: The Rocketeer
directors: Joe Johnston
actors: Billy Campbell, Jennifer Connelly, Alan Arkin, Timothy Dalton
----------------------
Movie title: The Muppet Christmas Carol
directors: Brian Henson
actors: Michael Caine, Dave Goelz, The Great Gonzo, Steve Whitmire
----------------------
Movie title: The Mighty Ducks
directors: Stephen Herek
actors: Emilio Estevez, Joss Ackland, Lane Smith, Heidi Kling
----------------------
Movie title: Newsies
directors: Kenny Ortega
actors: Christian Bale, Bill Pullman, Robert Duvall, Ann-Margret
----------------------
Movie title: Honey, I Blew Up the Kid
directors: Randal Kleiser
actors: Rick Moranis, Marcia Strassman, Robert Oliveri, Daniel Shalikar
----------------------
Movie title: Aladdin
directors: Ron Clements, John Musker
actors: Scott Weinger, Robin Williams, Linda Larkin, Jonathan Freeman
----------------------
Movie title: Cool Runnings
directors: Jon Turteltaub
actors: John Candy, Leon, Doug E. Doug, Rawle D. Lewis
----------------------
Movie title: Heidi
directors:
actors: Jason Robards, Jane Seymour, Patricia Neal, Siân Phillips
----------------------
Movie title: The Adventures of Huck Finn
directors: Stephen Sommers
actors: Elijah Wood, Courtney B. Vance, Robbie Coltrane, Jason Robards
----------------------
Movie title: The Nightmare Before Christmas
directors: Henry Selick
actors: Danny Elfman, Chris Sarandon, Catherine O'Hara, William Hickey
----------------------
Movie title: A Far Off Place
directors: Mikael Salomon
actors: Reese Witherspoon, Ethan Embry, Jack Thompson, Sarel Bok
----------------------
Movie title: Hocus Pocus
directors: Kenny Ortega
actors: Bette Midler, Sarah Jessica Parker, Kathy Najimy, Omri Katz
----------------------
Movie title: The Three Musketeers
directors: Stephen Herek
actors: Charlie Sheen, Kiefer Sutherland, Chris O'Donnell, Oliver Platt
----------------------
Movie title: Homeward Bound: The Incredible Journey
directors: Duwayne Dunham
actors: Michael J. Fox, Sally Field, Don Alder, Ed Bernard
----------------------
Movie title: White Fang 2: Myth of the White Wolf
directors: Ken Olin
actors: Scott Bairstow, Charmaine Craig, Al Harrington, Anthony Ruivivar
----------------------
Movie title: D2: The Mighty Ducks
directors: Sam Weisman
actors: Emilio Estevez, Kathryn Erbe, Michael Tucker, Jan Rubes
----------------------
Movie title: Angels in the Outfield
directors: William Dear
actors: Danny Glover, Brenda Fricker, Tony Danza, Christopher Lloyd
----------------------
Movie title: The Santa Clause
directors: John Pasquin
actors: Tim Allen, Judge Reinhold, Wendy Crewson, Eric Lloyd
----------------------
Movie title: Squanto: A Warrior's Tale
directors: Xavier Koller
actors: Adam Beach, Mandy Patinkin, Sheldon Peters Wolfchild, Irene Bedard
----------------------
Movie title: The Jungle Book
directors: Stephen Sommers
actors: Jason Scott Lee, Cary Elwes, Lena Headey, Sam Neill
----------------------
Movie title: Blank Check
directors: Rupert Wainwright
actors: Brian Bonsall, Karen Duffy, James Rebhorn, Jayne Atkinson
----------------------
Movie title: The Lion King
directors: Roger Allers, Rob Minkoff
actors: Matthew Broderick, Jeremy Irons, James Earl Jones, Whoopi Goldberg
----------------------
Movie title: Iron Will
directors: Charles Haid
actors: Mackenzie Astin, Kevin Spacey, David Ogden Stiers, August Schellenberg
----------------------
Movie title: Gordy
directors: Mark Lewis
actors: Kristy Young, Doug Stone, James Donadio, Deborah Hobart
----------------------
Movie title: Heavyweights
directors: Steven Brill
actors: Tom McGowan, Aaron Schwartz, Ben Stiller, David Goldman
----------------------
Movie title: Tall Tale
directors: Jeremiah S. Chechik
actors: Patrick Swayze, Oliver Platt, Roger Aaron Brown, Nick Stahl
----------------------
Movie title: Man of the House
directors: James Orr
actors: Chevy Chase, Farrah Fawcett, Jonathan Taylor Thomas, George Wendt
----------------------
Movie title: Pocahontas
directors: Mike Gabriel, Eric Goldberg
actors: Mel Gibson, Linda Hunt, Christian Bale, Joe Baker
----------------------
Movie title: Operation Dumbo Drop
directors: Simon Wincer
actors: Danny Glover, Ray Liotta, Denis Leary, Doug E. Doug
----------------------
Movie title: A Kid in King Arthur's Court
directors: Michael Gottlieb
actors: Thomas Ian Nicholas, Joss Ackland, Art Malik, Paloma Baeza
----------------------
Movie title: The Big Green
directors: Holly Goldberg Sloan
actors: Steve Guttenberg, Olivia d'Abo, Jay O. Sanders, John Terry
----------------------
Movie title: Tom and Huck
directors: Peter Hewitt
actors: Jonathan Taylor Thomas, Brad Renfro, Charles Rocket, Eric Schweig
----------------------
Movie title: A Goofy Movie
directors: Kevin Lima
actors: Bill Farmer, Jason Marsden, Jim Cummings, Kellie Martin
----------------------
Movie title: Toy Story
directors: John Lasseter
actors: Tom Hanks, Tim Allen, Don Rickles, Jim Varney
----------------------
Movie title: D3: The Mighty Ducks
directors: Robert Lieberman
actors: Emilio Estevez, Jeffrey Nordling, David Selby, Heidi Kling
----------------------
Movie title: The Hunchback of Notre Dame
directors: Gary Trousdale, Kirk Wise
actors: Demi Moore, Jason Alexander, Mary Kay Bergman, Corey Burton
----------------------
Movie title: First Kid
directors: David Mickey Evans
actors: Sinbad, Brock Pierce, Blake Boyd, Timothy Busfield
----------------------
Movie title: 101 Dalmatians
directors: Stephen Herek
actors: Glenn Close, Jeff Daniels, Joely Richardson, Joan Plowright
----------------------
Movie title: Muppet Treasure Island
directors: Brian Henson, David Lane
actors: Tim Curry, Billy Connolly, Jennifer Saunders, Kevin Bishop
----------------------
Movie title: James and the Giant Peach
directors: Henry Selick
actors: Paul Terry, Joanna Lumley, Pete Postlethwaite, Simon Callow
----------------------
Movie title: Homeward Bound II: Lost in San Francisco
directors: David R. Ellis
actors: Michael J. Fox, Sally Field, Ralph Waite, Al Michaels
----------------------
Movie title: That Darn Cat
directors: Bob Spiers
actors: Christina Ricci, Doug E. Doug, Dean Jones, George Dzundza
----------------------
Movie title:  The Wonderful World of Disney
directors: Gary Nadeau
actors: Paul Dooley, Matthew Lawrence, David Gallagher, Jack Coleman
----------------------
Movie title:  The Wonderful World of Disney
directors: Tony Bill
actors: Richard Dreyfuss, Elijah Wood, David O'Hara, Alex Trench
----------------------
Movie title: George of the Jungle
directors: Sam Weisman
actors: Brendan Fraser, Leslie Mann, Thomas Haden Church, Richard Roundtree
----------------------
Movie title: Hercules
directors: Ron Clements, John Musker
actors: Tate Donovan, Susan Egan, James Woods, Josh Keaton
----------------------
Movie title: Tower of Terror
directors:
actors:
----------------------
Movie title: Flubber
directors: Les Mayfield
actors: Robin Williams, Marcia Gay Harden, Christopher McDonald, Ted Levine
----------------------
Movie title: Mr. Magoo
directors: Stanley Tong
actors: Leslie Nielsen, Kelly Lynch, Matt Keeslar, Nick Chinlund
----------------------
Movie title: Beauty and the Beast: The Enchanted Christmas
directors: Andrew Knight
actors: Paige O'Hara, Robby Benson, Jerry Orbach, David Ogden Stiers
----------------------
Movie title: Jungle 2 Jungle
directors: John Pasquin
actors: Tim Allen, Martin Short, JoBeth Williams, Lolita Davidovich
----------------------
Movie title: RocketMan
directors: Stuart Gillard
actors: Harland Williams, Jessica Lundy, William Sadler, Jeffrey DeMunn
----------------------
Movie title: Under Wraps
directors: Greg Beeman
actors: Adam Wylie, Mario Yedidia, Clara Bryant, Ken Hudson Campbell
----------------------
Movie title: Northern Lights
directors: Linda Yellen
actors: Diane Keaton, Maury Chaykin, Joseph Cross, Kathleen York
----------------------
Movie title: Air Bud
directors: Charles Martin Smith
actors: Michael Jeter, Kevin Zegers, Wendy Makkena, Bill Cobbs
----------------------
Movie title: You Lucky Dog
directors: Paul Schneider
actors: Kirk Cameron, Chelsea Noble, John de Lancie, Christine Healy
----------------------
Movie title: Halloweentown
directors: Duwayne Dunham
actors: Debbie Reynolds, Kimberly J. Brown, Judith Hoag, Joey Zimmerman
----------------------
Movie title: The Wonderful Ice Cream Suit
directors: Stuart Gordon
actors: Joe Mantegna, Esai Morales, Edward James Olmos, Clifton Collins Jr.
----------------------
Movie title: Meet the Deedles
directors: Steve Boyum
actors: Paul Walker, Steve Van Wormer, A.J. Langer, John Ashton
----------------------
Movie title:  The Wonderful World of Disney
directors: Roger Young
actors: Whoopi Goldberg, Michael York, Paloma Baeza, Simon Fenton
----------------------
Movie title: Mulan
directors: Tony Bancroft, Barry Cook
actors: Ming-Na Wen, Eddie Murphy, BD Wong, Miguel Ferrer
----------------------
Movie title: The Parent Trap
directors: Nancy Meyers
actors: Lindsay Lohan, Dennis Quaid, Natasha Richardson, Elaine Hendrix
----------------------
Movie title: Pocahontas II: Journey to a New World
directors: Tom Ellery, Bradley Raymond
actors: Irene Bedard, Donal Gibson, Jim Cummings, Finola Hughes
----------------------
Movie title: Air Bud: Golden Receiver
directors: Richard Martin
actors: Kevin Zegers, Cynthia Stevenson, Tim Conway, Dick Martin
----------------------
Movie title: I'll Be Home for Christmas
directors: Arlene Sanford
actors: Jonathan Taylor Thomas, Jessica Biel, Adam LaVorgna, Gary Cole
----------------------
Movie title: Mighty Joe Young
directors: Ron Underwood
actors: Bill Paxton, Charlize Theron, Rade Serbedzija, Peter Firth
----------------------
Movie title: Brink!
directors: Greg Beeman
actors: Erik von Detten, Sam Horrigan, Christina Vidal, Robin Riker
----------------------
Movie title: A Bug's Life
directors: John Lasseter, Andrew Stanton
actors: Kevin Spacey, Dave Foley, Julia Louis-Dreyfus, Hayden Panettiere
----------------------
Movie title: The Lion King 2: Simba's Pride
directors: Darrell Rooney, Rob LaDuca
actors: Matthew Broderick, Neve Campbell, Andy Dick, Robert Guillaume
----------------------
Movie title:  The Wonderful World of Disney
directors: Rob Marshall
actors: Kathy Bates, Victor Garber, Alan Cumming, Audra McDonald
----------------------
Movie title: Don't Look Under the Bed
directors: Kenneth Johnson
actors: Erin Chambers, Ty Hodges, Robin Riker, Steve Valentine
----------------------
Movie title: Genius
directors: Rod Daniel
actors: Trevor Morgan, Emmy Rossum, Charles Fleischer, Yannick Bisson
----------------------
Movie title: The Thirteenth Year
directors: Duwayne Dunham
actors: Chez Starbuck, Justin Jon Ross, Courtnee Draper, Brent Briscoe
----------------------
Movie title: Johnny Tsunami
directors: Steve Boyum
actors: Cary-Hiroyuki Tagawa, Brandon Baker, Mary Page Keller, Yuji Okumoto
----------------------
Movie title: Can of Worms
directors: Paul Schneider
actors: Michael Shulman, Erika Christensen, Adam Wylie, Andrew Ducote
----------------------
Movie title: Zenon: Girl of the 21st Century
directors: Kenneth Johnson
actors: Kirsten Storms, Raven-Symoné, Bob Bancroft, Stuart Pankin
----------------------
Movie title: Horse Sense
directors: Greg Beeman
actors: Joey Lawrence, Andrew Lawrence, Susan Walters, M.C. Gainey
----------------------
Movie title: Endurance
directors: Leslie Woodhead, Bud Greenspan
actors: Haile Gebrselassie, Shawananness Gebrselassie, Yonas Zergaw, Tedesse Haile
----------------------
Movie title: Smart House
directors: LeVar Burton
actors: Kevin Kilner, Ryan Merriman, Katey Sagal, Jessica Steen
----------------------
Movie title: My Favorite Martian
directors: Donald Petrie
actors: Christopher Lloyd, Jeff Daniels, Elizabeth Hurley, Daryl Hannah
----------------------
Movie title: Doug's 1st Movie
directors: Maurice Joyce
actors: Thomas McHugh, Fred Newman, Chris Phillips, Constance Shulman
----------------------
Movie title: The Straight Story
directors: David Lynch
actors: Richard Farnsworth, Sissy Spacek, Jane Galloway Heitz, Joseph A. Carpenter
----------------------
Movie title: Tarzan
directors: Chris Buck, Kevin Lima
actors: Tony Goldwyn, Minnie Driver, Brian Blessed, Glenn Close
----------------------
Movie title: Inspector Gadget
directors: David Kellogg
actors: Matthew Broderick, Rupert Everett, Joely Fisher, Michelle Trachtenberg
----------------------
Movie title:  The Wonderful World of Disney
directors: Randall Miller
actors: Will Friedle, Matthew Lawrence, Gabrielle Union, Shawn Pyfrom
----------------------
Movie title: Mickey's Once Upon a Christmas
directors: Jun Falkenstein, Alex Mann, Bradley Raymond, Toby Shelton, Bill Speers
actors: Kelsey Grammer, Wayne Allwine, Russi Taylor, Tony Anselmo
----------------------
Movie title: Fantasia 2000
directors: James Algar, Gaëtan Brizzi, Paul Brizzi, Hendel Butoy, Francis Glebas, Eric Goldberg, Don Hahn, Pixote Hunt
actors: James Levine, Steve Martin, Itzhak Perlman, Quincy Jones
----------------------
Movie title: Toy Story 2
directors: John Lasseter, Ash Brannon, Lee Unkrich
actors: Tom Hanks, Tim Allen, Joan Cusack, Kelsey Grammer
----------------------
Movie title:  The Wonderful World of Disney
directors: Robert King
actors: Patrick Warburton, Britt Irvin, Kurt Fuller, Rebecca Jenkins
----------------------
Movie title: The Ultimate Christmas Present

directors: Greg Beeman
actors: Hallee Hirsh, Spencer Breslin, Hallie Todd, Brenda Song
----------------------
Movie title: Phantom of the Megaplex
directors: Blair Treu
actors: Taylor Handley, Corinne Bohrer, Caitlin Wachs, Jacob Smith
----------------------
Movie title: Mom's Got a Date with a Vampire
directors: Steve Boyum
actors: Matt O'Leary, Laura Vandervoort, Myles Jeffrey, Caroline Rhea
----------------------
Movie title: The Other Me
directors: Manny Coto
actors: Andrew Lawrence, Mark L. Taylor, Lori Hallier, Alison Pill
----------------------
Movie title: Quints
directors: Bill Corcoran
actors: Kimberly J. Brown, Daniel Roebuck, Elizabeth Morehead, Shadia Simmons
----------------------
Movie title: Ready to Run
directors: Duwayne Dunham
actors: Krystle Po, Jason Dohring, Lillian Hurst, Jon Brazier
----------------------
Movie title: Stepsister from Planet Weird
directors: Steve Boyum
actors: Courtnee Draper, Tamara Hope, Lance Guest, Khrystyne Haje
----------------------
Movie title: Miracle in Lane 2
directors: Greg Beeman
actors: Frankie Muniz, Rick Rossovich, Molly Hagan, Patrick Levis
----------------------
Movie title: Rip Girls
directors: Joyce Chopra
actors: Camilla Belle, Dwier Brown, Stacie Hess, Brian Stark
----------------------
Movie title: Alley Cats Strike
directors: Rod Daniel
actors: Kyle Schmid, Robert Ri'chard, Kaley Cuoco, Mimi Paley
----------------------
Movie title: The Color of Friendship
directors: Kevin Hooks
actors: Lindsey Haun, Shadia Simmons, Carl Lumbly, Penny Johnson Jerald
----------------------
Movie title: Up, Up, and Away!
directors: Robert Townsend
actors: Robert Townsend, Michael J. Pagan, Alex Datcher, Sherman Hemsley
----------------------
Movie title: Air Bud 3
directors: Bill Bannerman
actors: Kevin Zegers, Dale Midkiff, David Glyn-Jones, Caitlin Wachs
----------------------
Movie title: An Extremely Goofy Movie
directors: Douglas McCarthy
actors: Bill Farmer, Jason Marsden, Jeff Bennett, Jim Cummings
----------------------
Movie title: Whispers: An Elephant's Tale
directors: Dereck Joubert
actors: Angela Bassett, Joanna Lumley, Anne Archer, Debi Derryberry
----------------------
Movie title: Dinosaur
directors: Eric Leighton, Ralph Zondag
actors: D.B. Sweeney, Julianna Margulies, Samuel E. Wright, Alfre Woodard
----------------------
Movie title: The Kid
directors: Jon Turteltaub
actors: Bruce Willis, Spencer Breslin, Emily Mortimer, Lily Tomlin
----------------------
Movie title: The Little Mermaid 2: Return to the Sea
directors: Jim Kammerud, Brian Smith
actors: Tara Strong, Pat Carroll, Jodi Benson, Samuel E. Wright
----------------------
Movie title: Remember the Titans
directors: Boaz Yakin
actors: Denzel Washington, Will Patton, Wood Harris, Ryan Hurst
----------------------
Movie title: 102 Dalmatians
directors: Kevin Lima
actors: Glenn Close, Gérard Depardieu, Ioan Gruffudd, Alice Evans
----------------------
Movie title:  The Wonderful World of Disney
directors: Eric Champnella
actors: Bill Switzer, Randy Quaid, Holland Taylor, Ashley Gorrell
----------------------
Movie title:  The Wonderful World of Disney
directors: Tom Moore
actors: Drew Carey, Julia Louis-Dreyfus, Brent Spiner, Rene Auberjonois
----------------------
Movie title: The Emperor's New Groove
directors: Mark Dindal
actors: David Spade, John Goodman, Eartha Kitt, Patrick Warburton
----------------------
Movie title: The Tigger Movie
directors: Jun Falkenstein
actors: Jim Cummings, Nikita Hopkins, Ken Sansom, John Fiedler
----------------------
Movie title: Jett Jackson: The Movie
directors: Shawn Levy
actors: Lee Thompson Young, Lindy Booth, Nigel Shawn Williams, Ryan Sommers Baum
----------------------
Movie title: Mickey's Magical Christmas: Snowed in at the House of Mouse
directors: Tony Craig, Roberts Gannaway, Rick Calabash
actors: Carlos Alazraqui, Wayne Allwine, Tony Anselmo, Jeff Bennett
----------------------
Movie title: Motocrossed
directors: Steve Boyum
actors: Alana Austin, Trever O'Brien, Riley Smith, Mary-Margaret Humes
----------------------
Movie title: Recess: School's Out
directors: Chuck Sheetz
actors: Andrew Lawrence, Rickey D'Shon Collins, Jason Davis, Ashley Johnson
----------------------
Movie title: Lady and the Tramp 2: Scamp's Adventure
directors: Darrell Rooney, Jeannine Roussel
actors: Scott Wolf, Alyssa Milano, Chazz Palminteri, Jeff Bennett
----------------------
Movie title: Atlantis: The Lost Empire
directors: Gary Trousdale, Kirk Wise
actors: Michael J. Fox, Jim Varney, Corey Burton, Claudia Christian
----------------------
Movie title: Spirited Away
directors: Hayao Miyazaki
actors: Daveigh Chase, Suzanne Pleshette, Miyu Irino, Rumi Hiiragi
----------------------
Movie title: The Princess Diaries
directors: Garry Marshall
actors: Julie Andrews, Anne Hathaway, Hector Elizondo, Heather Matarazzo
----------------------
Movie title: Max Keeble's Big Move
directors: Tim Hill
actors: Alex D. Linz, Larry Miller, Jamie Kennedy, Zena Grey
----------------------
Movie title: Monsters, Inc.
directors: Pete Docter, David Silverman, Lee Unkrich
actors: Billy Crystal, John Goodman, Mary Gibbs, Steve Buscemi
----------------------
Movie title: 'Twas the Night
directors: Nick Castle
actors: Josh Zuckerman, Brenda Grate, Bryan Cranston, Jefferson Mappin
----------------------
Movie title: The Other Side of Heaven
directors: Mitch Davis
actors: Christopher Gorham, Anne Hathaway, Joe Folau, Nathaniel Lees
----------------------
Movie title: Halloweentown II: Kalabar's Revenge
directors: Mary Lambert
actors: Kimberly J. Brown, Judith Hoag, Daniel Kountz, Joey Zimmerman
----------------------
Movie title: The Poof Point
directors: Neal Israel
actors: Tahj Mowry, Dawnn Lewis, Mark Curry, Raquel Lee
----------------------
Movie title: Jumping Ship
directors: Michael Lange
actors: Joey Lawrence, Matthew Lawrence, Andrew Lawrence, Susan Walters
----------------------
Movie title: The Jennie Project
directors: Gary Nadeau
actors: Alex D. Linz, Sheila Kelley, Lance Guest, Abigail Mavity
----------------------
Movie title: Hounded
directors: Neal Israel
actors: Tahj Mowry, Craig Kirkwood, Shia LaBeouf, Ed Begley Jr.
----------------------
Movie title: The Luck of the Irish
directors: Paul Hoen
actors: Ryan Merriman, Henry Gibson, Alexis Lopez, Glenndon Chatman
----------------------
Movie title: Zenon: The Zequel
directors: Manny Coto
actors: Kirsten Storms, Shadia Simmons, Lauren Maltby, Susan Brady
----------------------
Movie title: The Scream Team
directors: Stuart Gillard
actors: Mark Rendall, Kat Dennings, Robert Bockstael, Eric Idle
----------------------
Movie title: A Ring of Endless Light
directors: Greg Beeman
actors: Mischa Barton, Ryan Merriman, Jared Padalecki, Scarlett Pomers
----------------------
Movie title: Gotta Kick It Up!
directors: Ramón Menéndez
actors: Camille Guaty, America Ferrera, Jhoanna Flores, Suilma Rodriguez
----------------------
Movie title: Get a Clue
directors: Maggie Greenwald
actors: Lindsay Lohan, Bug Hall, Ian Gomez, Brenda Song
----------------------
Movie title: Tru Confessions
directors: Paul Hoen
actors: Clara Bryant, Shia LaBeouf, Mare Winningham, William Francis McGuire
----------------------
Movie title: Cadet Kelly
directors: Larry Shaw
actors: Hilary Duff, Christy Carlson Romano, Gary Cole, Shawn Ashmore
----------------------
Movie title: Double Teamed
directors: Duwayne Dunham
actors: Poppi Monroe, Annie McElwain, Teal Redmann, Nick Searcy
----------------------
Movie title: Air Bud: Seventh Inning Fetch
directors: Robert Vince
actors: Jeffrey Ballard, Jay Brazeau, Jason Bryden, Patrick Cranshaw
----------------------
Movie title: Snow Dogs
directors: Brian Levant
actors: Cuba Gooding Jr., James Coburn, Sisqó, Nichelle Nichols
----------------------
Movie title: Peter Pan 2: Return to Never Land
directors: Robin Budd, Donovan Cook
actors: Blayne Weaver, Harriet Owen, Corey Burton, Jeff Bennett
----------------------
Movie title: Cinderella 2: Dreams Come True
directors: John Kafka
actors: Jennifer Hale, Rob Paulsen, Corey Burton, Andre Stojka
----------------------
Movie title: Lilo & Stitch
directors: Dean DeBlois, Chris Sanders
actors: Daveigh Chase, Chris Sanders, Tia Carrere, David Ogden Stiers
----------------------
Movie title: The Country Bears
directors: Peter Hastings
actors: Haley Joel Osment, Diedrich Bader, Candy Ford, James Gammon
----------------------
Movie title: Tuck Everlasting
directors: Jay Russell
actors: Alexis Bledel, Jonathan Jackson, Sissy Spacek, William Hurt
----------------------
Movie title: The Santa Clause 2
directors: Michael Lembeck
actors: Tim Allen, Spencer Breslin, Elizabeth Mitchell, Eric Lloyd
----------------------
Movie title: Treasure Planet
directors: Ron Clements, John Musker
actors: Joseph Gordon-Levitt, Emma Thompson, Martin Short, Roscoe Lee Browne
----------------------
Movie title: Winnie the Pooh: A Very Merry Pooh Year
directors: Gary Katona, Ed Wexler, Jamie Mitchell
actors: Jim Cummings, Peter Cullen, John Fiedler, Michael Gough
----------------------
Movie title: The Rookie
directors: John Lee Hancock
actors: Dennis Quaid, J.D. Evermore, Rachel Griffiths, Jay Hernandez
----------------------
Movie title: Kim Possible: A Sitch in Time
directors: Steve Loter
actors: Christy Carlson Romano, Will Friedle, Nancy Cartwright, Tahj Mowry
----------------------
Movie title: Full-Court Miracle
directors: Stuart Gillard
actors: Alex D. Linz, Richard T. Jones, R.H. Thomson, Sean Marquette
----------------------
Movie title: The Cheetah Girls
directors: Oz Scott
actors: Raven-Symoné, Adrienne Houghton, Kiely Williams, Sabrina Bryan
----------------------
Movie title: Eddie's Million Dollar Cook-Off
directors: Paul Hoen
actors: Taylor Ball, Orlando Brown, Reiley McClendon, Mark L. Taylor
----------------------
Movie title: The Even Stevens Movie
directors: Sean McNamara
actors: Shia LaBeouf, Christy Carlson Romano, Donna Pescow, Tom Virtue
----------------------
Movie title: Right on Track
directors: Duwayne Dunham
actors: Beverley Mitchell, Brie Larson, Jon Lindstrom, Jodi Russell
----------------------
Movie title: You Wish!
directors: Paul Hoen
actors: A.J. Trauth, Spencer Breslin, Lalaine, Tim Reid
----------------------
Movie title: Air Bud: Spikes Back
directors: Mike Southon
actors: Darren J. Birch, Christopher Bishop, Tyler Boissonnault, J. Winston Carroll
----------------------
Movie title: Brother Bear
directors: Aaron Blaise, Robert Walker
actors: Joaquin Phoenix, Jeremy Suarez, Rick Moranis, Jason Raize
----------------------
Movie title: 101 Dalmatians 2: Patch's London Adventure
directors: Jim Kammerud, Brian Smith
actors: Barry Bostwick, Jason Alexander, Martin Short, Bobby Lockwood
----------------------
Movie title: The Jungle Book 2
directors: Steve Trenbirth
actors: John Goodman, Haley Joel Osment, Tony Jay, Mae Whitman
----------------------
Movie title: Inspector Gadget 2
directors: Alex Zamm
actors: French Stewart, Elaine Hendrix, Tony Martin, Caitlin Wachs
----------------------
Movie title: Piglet's Big Movie
directors: Francis Glebas
actors: John Fiedler, Jim Cummings, Ken Sansom, Peter Cullen
----------------------
Movie title: Holes
directors: Andrew Davis
actors: Shia LaBeouf, Sigourney Weaver, Jon Voight, Tim Blake Nelson
----------------------
Movie title: Atlantis: Milo's Return
directors: Victor Cook, Toby Shelton, Tad Stones
actors: James Arnold Taylor, Cree Summer, John Mahoney, Jacqueline Obradors
----------------------
Movie title: Lizzie McGuire
directors: Jim Fall
actors: Hilary Duff, Adam Lamberg, Clayton Snyder, Hallie Todd
----------------------
Movie title: Pirates of the Caribbean: The Curse of the Black Pearl
directors: Gore Verbinski
actors: Johnny Depp, Geoffrey Rush, Orlando Bloom, Keira Knightley
----------------------
Movie title: Freaky Friday
directors: Mark Waters
actors: Jamie Lee Curtis, Lindsay Lohan, Mark Harmon, Harold Gould
----------------------
Movie title: George of the Jungle 2
directors: David Grossman
actors: Christopher Showerman, Julie Benz, Angus T. Jones, Thomas Haden Church
----------------------
Movie title: The Haunted Mansion
directors: Rob Minkoff
actors: Eddie Murphy, Marsha Thomason, Jennifer Tilly, Terence Stamp
----------------------
Movie title: The Young Black Stallion
directors: Simon Wincer
actors: Biana Tamimi, Richard Romanus, Patrick Elyas, Gérard Rudolf
----------------------
Movie title: Finding Nemo
directors: Andrew Stanton, Lee Unkrich
actors: Albert Brooks, Ellen DeGeneres, Alexander Gould, Willem Dafoe
----------------------
Movie title: Going to the Mat
directors: Stuart Gillard
actors: Andrew Lawrence, Khleo Thomas, Alessandra Torresani, Wayne Brady
----------------------
Movie title: Pixel Perfect
directors: Mark A.Z. Dippé
actors: Raviv Ullman, Leah Pipes, Spencer Redford, Chad 'Chato' Alger
----------------------
Movie title: Zenon: Z3
directors: Steve Rash
actors: Kirsten Storms, Lauren Maltby, Alyson Morgan, Stuart Pankin
----------------------
Movie title: Halloweentown High
directors: Mark A.Z. Dippé
actors: Kimberly J. Brown, Debbie Reynolds, Judith Hoag, Joey Zimmerman
----------------------
Movie title: Tiger Cruise
directors: Duwayne Dunham
actors: Hayden Panettiere, Bill Pullman, Troy Evans, Bianca Collins
----------------------
Movie title: Stuck in the Suburbs
directors: Savage Steve Holland
actors: Danielle Panabaker, Brenda Song, Amanda Shaw, CiCi Hedgpeth
----------------------
Movie title: Teacher's Pet
directors: Timothy Björklund
actors: Nathan Lane, Shaun Fleming, David Ogden Stiers, Kelsey Grammer
----------------------
Movie title: Miracle
directors: Gavin O'Connor
actors: Kurt Russell, Patricia Clarkson, Nathan West, Noah Emmerich
----------------------
Movie title: Confessions of a Teenage Drama Queen
directors: Sara Sugarman
actors: Lindsay Lohan, Megan Fox, Adam Garcia, Glenne Headly
----------------------
Movie title: Home on the Range
directors: Will Finn, John Sanford
actors: Judi Dench, Cuba Gooding Jr., Jennifer Tilly, Randy Quaid
----------------------
Movie title: Winnie the Pooh: Springtime with Roo
directors: Saul Blinkoff, Elliot M. Bour
actors: Jim Cummings, Ken Sansom, Jimmy Bennett, David Ogden Stiers
----------------------
Movie title: Around the World in 80 Days
directors: Frank Coraci
actors: Jackie Chan, Steve Coogan, Jim Broadbent, Kathy Bates
----------------------
Movie title: Mickey, Donald, Goofy: The Three Musketeers
directors: Donovan Cook
actors: Wayne Allwine, Tony Anselmo, Bill Farmer, Russi Taylor
----------------------
Movie title: The Princess Diaries 2: Royal Engagement
directors: Garry Marshall
actors: Anne Hathaway, Callum Blue, Julie Andrews, Hector Elizondo
----------------------
Movie title: Howl's Moving Castle
directors: Hayao Miyazaki
actors: Chieko Baishô, Takuya Kimura, Tatsuya Gashûin, Akihiro Miwa
----------------------
Movie title: Mulan II
directors: Darrell Rooney, Lynne Southerland
actors: Ming-Na Wen, BD Wong, Mark Moseley, Lucy Liu
----------------------
Movie title: National Treasure
directors: Jon Turteltaub
actors: Nicolas Cage, Diane Kruger, Justin Bartha, Sean Bean
----------------------
Movie title: Mickey's Twice Upon a Christmas
directors: Carole Holliday, Matthew O'Callaghan, Theresa Cullen
actors: Wayne Allwine, Tony Anselmo, Jeff Bennett, Jim Cummings
----------------------
Movie title: The Incredibles
directors: Brad Bird
actors: Craig T. Nelson, Samuel L. Jackson, Holly Hunter, Jason Lee
----------------------
Movie title: The Lion King 3: Hakuna Matata
directors: Bradley Raymond
actors: Nathan Lane, Ernie Sabella, Julie Kavner, Jerry Stiller
----------------------
Movie title:  The Wonderful World of Disney
directors: Kathleen Marshall
actors: Carol Burnett, Tracey Ullman, Denis O'Hare, Zooey Deschanel
----------------------
Movie title: Kim Possible: So the Drama
directors: Steve Loter
actors: Christy Carlson Romano, Will Friedle, Nancy Cartwright, Tahj Mowry
----------------------
Movie title: Go Figure
directors: Francine McDougall
actors: Jordan Danger, Whitney Sloan, Cristine Rose, Ryan Malgarini
----------------------
Movie title: Life Is Ruff
directors: Charles Haid
actors: Kyle Massey, Kay Panabaker, Mitchel Musso, Carter Jenkins
----------------------
Movie title: The Proud Family Movie
directors: Bruce W. Smith
actors: Kyla Pratt, Tommy Davidson, Paula Jai Parker, Jo Marie Payton
----------------------
Movie title: Kronk's New Groove
directors: Saul Blinkoff, Elliot M. Bour
actors: Patrick Warburton, Tracey Ullman, Eartha Kitt, David Spade
----------------------
Movie title: Twitches
directors: Stuart Gillard
actors: Tia Mowry-Hardrict, Tamera Mowry-Housley, Kristen Wilson, Patrick Fabian
----------------------
Movie title: The Greatest Game Ever Played
directors: Bill Paxton
actors: Shia LaBeouf, Stephen Dillane, Elias Koteas, James Paxton
----------------------
Movie title: Lilo & Stitch 2: Stitch Has a Glitch
directors: Michael LaBash, Tony Leondis
actors: Chris Sanders, Dakota Fanning, Tia Carrere, David Ogden Stiers
----------------------
Movie title: Pooh's Heffalump Movie
directors: Frank Nissen
actors: Jim Cummings, Brenda Blethyn, Kyle Stanger, John Fiedler
----------------------
Movie title: The Pacifier
directors: Adam Shankman
actors: Vin Diesel, Brittany Snow, Max Thieriot, Brad Garrett
----------------------
Movie title: Ice Princess
directors: Tim Fywell
actors: Michelle Trachtenberg, Kim Cattrall, Trevor Blumas, Joan Cusack
----------------------
Movie title: Sky High
directors: Mike Mitchell
actors: Kurt Russell, Kelly Preston, Michael Angarano, Danielle Panabaker
----------------------
Movie title: Pooh's Heffalump Halloween Movie
directors: Saul Blinkoff, Elliot M. Bour
actors: Jimmy Bennett, Peter Cullen, Jim Cummings, John Fiedler
----------------------
Movie title: Herbie Fully Loaded
directors: Angela Robinson
actors: Lindsay Lohan, Michael Keaton, Cheryl Hines, Breckin Meyer
----------------------
Movie title: Chicken Little
directors: Mark Dindal
actors: Zach Braff, Joan Cusack, Garry Marshall, Don Knotts
----------------------
Movie title: Valiant
directors: Gary Chapman
actors: Ewan McGregor, Ricky Gervais, Tim Curry, Jim Broadbent
----------------------
Movie title: The Chronicles of Narnia: The Lion, the Witch and the Wardrobe
directors: Andrew Adamson
actors: Tilda Swinton, Georgie Henley, William Moseley, Skandar Keynes
----------------------
Movie title: Buffalo Dreams
directors: David Jackson
actors: Simon Baker, Duy Beck, Roy J. Cohoe, Tatiana Galindo
----------------------
Movie title: Now You See It...
directors: Duwayne Dunham
actors: Aly Michalka, Johnny Pacar, Frank Langella, Chris Olivero
----------------------
Movie title: Read It and Weep
directors: Paul Hoen
actors: Kay Panabaker, Danielle Panabaker, Alexandra Krosney, Marquise C. Brown
----------------------
Movie title: Wendy Wu: Homecoming Warrior
directors: John Laing
actors: Brenda Song, Shin Koyamada, Susan Chuang, Justin Chon
----------------------
Movie title: Cow Belles
directors: Francine McDougall
actors: Aly Michalka, AJ Michalka, Jack Coleman, Sheila McCarthy
----------------------
Movie title: The Cheetah Girls 2
directors: Kenny Ortega
actors: Raven-Symoné, Adrienne Houghton, Sabrina Bryan, Kiely Williams
----------------------
Movie title: Air Buddies
directors: Robert Vince
actors: Cascy Beddow, Jane Carr, Kelly Chapek, Patrick Cranshaw
----------------------
Movie title: Return to Halloweentown
directors: David Jackson
actors: Sara Paxton, Judith Hoag, Lucas Grabeel, Joey Zimmerman
----------------------
Movie title: High School Musical
directors: Kenny Ortega
actors: Zac Efron, Vanessa Hudgens, Ashley Tisdale, Lucas Grabeel
----------------------
Movie title: Brother Bear 2
directors: Ben Gluck
actors: Patrick Dempsey, Mandy Moore, Jeremy Suarez, Rick Moranis

----------------------
Movie title: The Fox and the Hound 2
directors: Jim Kammerud
actors: Reba McEntire, Patrick Swayze, Jonah Bobo, Harrison Fahn
----------------------
Movie title: Glory Road
directors: James Gartner
actors: Josh Lucas, Derek Luke, Austin Nichols, Jon Voight
----------------------
Movie title: Bambi and the Great Prince of the Forest
directors: Brian Pimental
actors: Patrick Stewart, Alexander Gould, Keith Ferguson, Brendon Baerg
----------------------
Movie title: Eight Below
directors: Frank Marshall
actors: Paul Walker, Jason Biggs, Bruce Greenwood, Moon Bloodgood
----------------------
Movie title: The Shaggy Dog
directors: Brian Robbins
actors: Tim Allen, Kristin Davis, Craig Kilborn, Zena Grey
----------------------
Movie title: The Wild
directors: Steve 'Spaz' Williams
actors: Kiefer Sutherland, Jim Belushi, Eddie Izzard, Janeane Garofalo
----------------------
Movie title: Pirates of the Caribbean: Dead Man's Chest
directors: Gore Verbinski
actors: Johnny Depp, Orlando Bloom, Keira Knightley, Jack Davenport
----------------------
Movie title: Invincible
directors: Ericson Core
actors: Mark Wahlberg, Greg Kinnear, Elizabeth Banks, Kevin Conway
----------------------
Movie title: The Santa Clause 3: The Escape Clause
directors: Michael Lembeck
actors: Tim Allen, Martin Short, Elizabeth Mitchell, Eric Lloyd
----------------------
Movie title: Cars
directors: John Lasseter, Joe Ranft
actors: Owen Wilson, Bonnie Hunt, Paul Newman, Larry the Cable Guy
----------------------
Movie title: My Friends Tigger and Pooh - Super Sleuth Christmas Movie
directors: Don MacKinnon
actors: Dee Bradley Baker, Mikaila Baumel, Kimberlea Berg, Max Burkholder
----------------------
Movie title: Twitches Too
directors: Stuart Gillard
actors: Tia Mowry-Hardrict, Tamera Mowry-Housley, Kristen Wilson, Patrick Fabian
----------------------
Movie title: The Secret of the Magic Gourd
directors: Frankie Chung
actors: Corbin Bleu, Peisi Chen, Aaron Michael Drozin, Drake Johnston
----------------------
Movie title: High School Musical 2
directors: Kenny Ortega
actors: Zac Efron, Vanessa Hudgens, Ashley Tisdale, Lucas Grabeel
----------------------
Movie title: National Treasure: Book of Secrets
directors: Jon Turteltaub
actors: Nicolas Cage, Diane Kruger, Justin Bartha, Jon Voight
----------------------
Movie title: Enchanted
directors: Kevin Lima
actors: Amy Adams, Susan Sarandon, James Marsden, Patrick Dempsey
----------------------
Movie title: The Game Plan
directors: Andy Fickman
actors: Dwayne Johnson, Kyra Sedgwick, Madison Pettis, Roselyn Sanchez
----------------------
Movie title: Ratatouille
directors: Brad Bird, Jan Pinkava
actors: Brad Garrett, Lou Romano, Patton Oswalt, Ian Holm
----------------------
Movie title: Pirates of the Caribbean: At World's End
directors: Gore Verbinski
actors: Johnny Depp, Orlando Bloom, Keira Knightley, Geoffrey Rush
----------------------
Movie title: Underdog
directors: Frederik Du Chau
actors: Peter Dinklage, Jason Lee, Amy Adams, Jim Belushi
----------------------
Movie title: Cinderella 3: A Twist in Time
directors: Frank Nissen
actors: Jennifer Hale, Christopher Daniel Barnes, Susanne Blakeslee, Tress MacNeille
----------------------
Movie title: Meet the Robinsons
directors: Stephen J. Anderson
actors: Daniel Hansen, Wesley Singerman, Angela Bassett, Jordan Fry
----------------------
Movie title: Jump In!
directors: Paul Hoen
actors: Corbin Bleu, Keke Palmer, David Reivers, Shanica Knowles
----------------------
Movie title: Johnny Kapahala: Back on Board
directors: Eric Bross
actors: Brandon Baker, Jake T. Austin, Cary-Hiroyuki Tagawa, Robyn Lively
----------------------
Movie title: Bridge to Terabithia
directors: Gabor Csupo
actors: Josh Hutcherson, AnnaSophia Robb, Zooey Deschanel, Robert Patrick
----------------------
Movie title: The Little Mermaid: Ariel's Beginning
directors: Peggy Holmes
actors: Jodi Benson, Samuel E. Wright, Jim Cummings, Sally Field
----------------------
Movie title: Tinker Bell
directors: Bradley Raymond
actors: Mae Whitman, Kristin Chenoweth, Raven-Symoné, Lucy Liu
----------------------
Movie title: Bolt
directors: Byron Howard, Chris Williams
actors: John Travolta, Miley Cyrus, Susie Essman, Mark Walton
----------------------
Movie title: Camp Rock
directors: Matthew Diamond
actors: Demi Lovato, Joe Jonas, Meaghan Martin, Maria Canals-Barrera
----------------------
Movie title: Minutemen
directors: Lev L. Spiro
actors: Jason Dolley, Luke Benward, Nicholas Braun, Chelsea Kane
----------------------
Movie title: Snow Buddies
directors: Robert Vince
actors: Jim Belushi, Jimmy Bennett, Lothaire Bluteau, Jason Bryden
----------------------
Movie title: Beverly Hills Chihuahua
directors: Raja Gosnell
actors: Drew Barrymore, George Lopez, Piper Perabo, Manolo Cardona
----------------------
Movie title: College Road Trip
directors: Roger Kumble
actors: Raven-Symoné, Martin Lawrence, Kym Whitley, Adam LeFevre
----------------------
Movie title: WALL·E
directors: Andrew Stanton
actors: Ben Burtt, Elissa Knight, Jeff Garlin, Fred Willard
----------------------
Movie title: High School Musical 3
directors: Kenny Ortega
actors: Zac Efron, Vanessa Hudgens, Ashley Tisdale, Lucas Grabeel
----------------------
Movie title: The Chronicles of Narnia: Prince Caspian
directors: Andrew Adamson
actors: Ben Barnes, Skandar Keynes, Georgie Henley, William Moseley
----------------------
Movie title: The Cheetah Girls: One World
directors: Paul Hoen
actors: Adrienne Houghton, Sabrina Bryan, Kiely Williams, Roshan Seth
----------------------
Movie title: Bedtime Stories
directors: Adam Shankman
actors: Adam Sandler, Keri Russell, Courteney Cox, Guy Pearce
----------------------
Movie title: Wizards of Waverly Place: The Movie
directors: Lev L. Spiro
actors: Selena Gomez, David Henrie, Jake T. Austin, Jennifer Stone
----------------------
Movie title: Santa Buddies
directors: Robert Vince
actors: Craig Anton, Andrew Astor, Charisse Baker, Danny Woodburn
----------------------
Movie title: Tigger & Pooh and a Musical Too
directors: David Hartman
actors: Jim Cummings, Chloë Grace Moretz, Peter Cullen, Ken Sansom
----------------------
Movie title: Hatching Pete
directors: Stuart Gillard
actors: Jason Dolley, Mitchel Musso, Tiffany Thornton, Josie Loren
----------------------
Movie title: Dadnapped
directors: Paul Hoen
actors: Emily Osment, David Henrie, Jason Earles, Jonathan Keltz
----------------------
Movie title: G-Force
directors: Hoyt Yeatman
actors: Will Arnett, Penélope Cruz, Zach Galifianakis, Bill Nighy
----------------------
Movie title: Space Buddies
directors: Robert Vince
actors: F.T. Anderson, Diedrich Bader, Field Cate, Kendall Cross
----------------------
Movie title: Princess Protection Program
directors: Allison Liddi-Brown
actors: Demi Lovato, Selena Gomez, Nicholas Braun, Molly Hagan
----------------------
Movie title: A Christmas Carol
directors: Robert Zemeckis
actors: Jim Carrey, Gary Oldman, Colin Firth, Steve Valentine
----------------------
Movie title: Tinker Bell and the Lost Treasure
directors: Klay Hall
actors: Mae Whitman, Jesse McCartney, Jane Horrocks, Lucy Liu
----------------------
Movie title: Old Dogs
directors: Walt Becker
actors: Robin Williams, John Travolta, Seth Green, Kelly Preston
----------------------
Movie title: Ponyo
directors: Hayao Miyazaki
actors: Cate Blanchett, Matt Damon, Liam Neeson, Tomoko Yamaguchi
----------------------
Movie title: The Princess and the Frog
directors: Ron Clements, John Musker
actors: Anika Noni Rose, Keith David, Oprah Winfrey, Bruno Campos
----------------------
Movie title: Up
directors: Pete Docter, Bob Peterson
actors: Edward Asner, Jordan Nagai, John Ratzenberger, Christopher Plummer
----------------------
Movie title: Hannah Montana: The Movie
directors: Peter Chelsom
actors: Miley Cyrus, Emily Osment, Billy Ray Cyrus, Jason Earles
----------------------
Movie title: Race to Witch Mountain
directors: Andy Fickman
actors: Dwayne Johnson, Carla Gugino, AnnaSophia Robb, Alexander Ludwig
----------------------
Movie title: Toy Story 3
directors: Lee Unkrich
actors: Tom Hanks, Tim Allen, Joan Cusack, Ned Beatty
----------------------
Movie title: Prince of Persia: The Sands of Time
directors: Mike Newell
actors: Jake Gyllenhaal, Gemma Arterton, Ben Kingsley, Alfred Molina
----------------------
Movie title: The Search for Santa Paws
directors: Robert Vince
actors: Reese Alexander, Diedrich Bader, Sahar Biniaz, Jan Bos
----------------------
Movie title: Avalon High
directors: Stuart Gillard
actors: Britt Robertson, Samuel Levi, Gregg Sulkin, Joey Pollari
----------------------
Movie title: TRON: Legacy
directors: Joseph Kosinski
actors: Jeff Bridges, Garrett Hedlund, Olivia Wilde, Bruce Boxleitner
----------------------
Movie title: Alice in Wonderland
directors: Tim Burton
actors: Mia Wasikowska, Johnny Depp, Helena Bonham Carter, Anne Hathaway
----------------------
Movie title: Den Brother
directors: Mark L. Taylor
actors: Hutch Dano, Genevieve Hannelius, Vicki Lewis, Kelsey Asbille
----------------------
Movie title: Camp Rock 2: The Final Jam
directors: Paul Hoen
actors: Demi Lovato, Joe Jonas, Nick Jonas, Kevin Jonas
----------------------
Movie title: Secretariat
directors: Randall Wallace
actors: Diane Lane, John Malkovich, Margo Martindale, Nelsan Ellis
----------------------
Movie title: Tangled
directors: Nathan Greno, Byron Howard
actors: Mandy Moore, Zachary Levi, Donna Murphy, Ron Perlman
----------------------
Movie title: Tinker Bell and the Great Fairy Rescue
directors: Bradley Raymond
actors: Mae Whitman, Lauren Mote, Michael Sheen, Pamela Adlon
----------------------
Movie title: The Sorcerer's Apprentice
directors: Jon Turteltaub
actors: Nicolas Cage, Jay Baruchel, Alfred Molina, Teresa Palmer
----------------------
Movie title: StarStruck
directors: Michael Grossman
actors: Sterling Knight, Danielle Campbell, Maggie Castle, Brandon Mychal Smith
----------------------
Movie title: Mars Needs Moms
directors: Simon Wells
actors: Seth Green, Joan Cusack, Dan Fogler, Elisabeth Harnois
----------------------
Movie title: Geek Charming
directors: Jeffrey Hornaday
actors: Sarah Hyland, Matt Prokop, Sasha Pieterse, Jordan Nichols
----------------------
Movie title: Good Luck Charlie, It's Christmas!
directors: Arlene Sanford
actors: Bridgit Mendler, Leigh-Allyn Baker, Bradley Steven Perry, Mia Talerico
----------------------
Movie title: Phineas and Ferb the Movie: Across the 2nd Dimension
directors: Robert Hughes, Dan Povenmire, Jay Lender, Jeff 'Swampy' Marsh, Kyle Menke
actors: Vincent Martella, Ashley Tisdale, Thomas Brodie-Sangster, Caroline Rhea
----------------------
Movie title: Cars 2
directors: John Lasseter, Bradford Lewis
actors: Owen Wilson, Larry the Cable Guy, Michael Caine, Emily Mortimer
----------------------
Movie title: Pirates of the Caribbean: On Stranger Tides
directors: Rob Marshall
actors: Johnny Depp, Penélope Cruz, Ian McShane, Geoffrey Rush
----------------------
Movie title: Spooky Buddies
directors: Robert Vince
actors: Tucker Albrizzi, Diedrich Bader, Ameko Eks Mass Carroll, Max Charles
----------------------
Movie title: The Muppets
directors: James Bobin
actors: Amy Adams, Jason Segel, Chris Cooper, Rashida Jones
----------------------
Movie title: Once Upon a Warrior
directors: Prakash Kovelamudi
actors: Siddharth, Shruti Haasan, Lakshmi Manchu, Ravi Babu
----------------------
Movie title: The Suite Life Movie
directors: Sean McNamara
actors: Cole Sprouse, Dylan Sprouse, Brenda Song, Debby Ryan
----------------------
Movie title: Sharpay's Fabulous Adventure
directors: Michael Lembeck
actors: Ashley Tisdale, Austin Butler, Cameron Goodman, Bradley Steven Perry
----------------------
Movie title: Lemonade Mouth
directors: Patricia Riggen
actors: Bridgit Mendler, Adam Hicks, Hayley Kiyoko, Naomi Scott
----------------------
Movie title: Winnie the Pooh
directors: Stephen J. Anderson, Don Hall
actors: Jim Cummings, Craig Ferguson, John Cleese, Bud Luckey
----------------------
Movie title: Beverly Hills Chihuahua 2
directors: Alex Zamm
actors: Marcus Coloma, Erin Cahill, Susan Blakely, Lupe Ontiveros
----------------------
Movie title: Prom
directors: Joe Nussbaum
actors: Aimee Teegarden, Thomas McDonell, DeVaughn Nixon, Danielle Campbell
----------------------
Movie title: Secret of the Wings
directors: Roberts Gannaway, Peggy Holmes
actors: Mae Whitman, Lucy Hale, Timothy Dalton, Jeff Bennett
----------------------
Movie title: Girl Vs. Monster
directors: Stuart Gillard
actors: Olivia Holt, Kerris Dorsey, Brendan Meyer, Katherine McNamara
----------------------
Movie title: Santa Paws 2: The Santa Pups
directors: Robert Vince
actors: Cheryl Ladd, Danny Woodburn, Kaitlyn Maher, Pat Finn
----------------------
Movie title: Sofia the First: Once Upon a Princess
directors: Jamie Mitchell
actors: Ariel Winter, Wayne Brady, Jim Cummings, Ashley Eckstein
----------------------
Movie title: Radio Rebel
directors: Peter Howitt
actors: Debby Ryan, Sarena Parmar, Adam DiMarco, Atticus Mitchell
----------------------
Movie title: Let It Shine
directors: Paul Hoen
actors: Tyler James Williams, Coco Jones, Trevor Jackson, Brandon Mychal Smith
----------------------
Movie title: Beverly Hills Chihuahua 3: Viva La Fiesta!
directors: Lev L. Spiro
actors: Marcus Coloma, Erin Cahill, Cedric Yarbrough, Frances Fisher
----------------------
Movie title: Treasure Buddies
directors: Robert Vince
actors: Tucker Albrizzi, Adam Alexi-Malle, Tim Conway, Mason Cook
----------------------
Movie title: The Secret World of Arrietty
directors: Hiromasa Yonebayashi
actors: Bridgit Mendler, Amy Poehler, Will Arnett, Tom Holland
----------------------
Movie title: Frankenweenie
directors: Tim Burton
actors: Winona Ryder, Catherine O'Hara, Martin Short, Martin Landau
----------------------
Movie title: Wreck-It Ralph
directors: Rich Moore
actors: John C. Reilly, Jack McBrayer, Jane Lynch, Sarah Silverman
----------------------
Movie title: Frenemies
directors: Daisy von Scherler Mayer
actors: Bella Thorne, Zendaya, Mary Mouser, Nick Robinson
----------------------
Movie title: The Odd Life of Timothy Green
directors: Peter Hedges
actors: Jennifer Garner, Joel Edgerton, CJ Adams, Odeya Rush
----------------------
Movie title: John Carter
directors: Andrew Stanton
actors: Taylor Kitsch, Lynn Collins, Willem Dafoe, Samantha Morton
----------------------
Movie title: Brave
directors: Mark Andrews, Brenda Chapman, Steve Purcell
actors: Kelly Macdonald, Billy Connolly, Emma Thompson, Julie Walters
----------------------
Movie title: Monsters University
directors: Dan Scanlon
actors: Billy Crystal, John Goodman, Steve Buscemi, Helen Mirren
----------------------
Movie title: Teen Beach Movie
directors: Jeffrey Hornaday
actors: Ross Lynch, Maia Mitchell, Gracie Gillam, Garrett Clayton
----------------------
Movie title: Saving Mr. Banks
directors: John Lee Hancock
actors: Emma Thompson, Tom Hanks, Annie Rose Buckley, Colin Farrell

----------------------
Movie title: Planes
directors: Klay Hall
actors: Carlos Alazraqui, Dane Cook, Stacy Keach, Brad Garrett
----------------------
Movie title: Super Buddies
directors: Robert Vince
actors: Trey Loney, John Ratzenberger, Michael Teigen, Sam Adler
----------------------
Movie title: Frozen
directors: Chris Buck, Jennifer Lee
actors: Kristen Bell, Idina Menzel, Jonathan Groff, Josh Gad
----------------------
Movie title: Oz the Great and Powerful
directors: Sam Raimi
actors: James Franco, Michelle Williams, Rachel Weisz, Mila Kunis
----------------------
Movie title: The Lone Ranger
directors: Gore Verbinski
actors: Johnny Depp, Armie Hammer, William Fichtner, Tom Wilkinson
----------------------
Movie title: How to Build a Better Boy
directors: Paul Hoen
actors: China Anne McClain, Kelli Berglund, Marshall Williams, Matt Shively
----------------------
Movie title: Zapped
directors: Peter DeLuise
actors: Zendaya, Chanelle Peloso, Spencer Boldman, Emilia McCarthy
----------------------
Movie title: Cloud 9
directors: Paul Hoen
actors: Luke Benward, Dove Cameron, Mike C. Manning, Kiersey Clemons
----------------------
Movie title: The Pirate Fairy
directors: Peggy Holmes
actors: Mae Whitman, Christina Hendricks, Tom Hiddleston, Lucy Liu
----------------------
Movie title: Into the Woods
directors: Rob Marshall
actors: Anna Kendrick, Meryl Streep, Chris Pine, Emily Blunt
----------------------
Movie title: Alexander and the Terrible, Horrible, No Good, Very Bad Day
directors: Miguel Arteta
actors: Steve Carell, Jennifer Garner, Ed Oxenbould, Dylan Minnette
----------------------
Movie title: Million Dollar Arm
directors: Craig Gillespie
actors: Jon Hamm, Aasif Mandvi, Alan Arkin, Suraj Sharma
----------------------
Movie title: Planes: Fire & Rescue
directors: Roberts Gannaway
actors: Dane Cook, Ed Harris, Julie Bowen, Curtis Armstrong
----------------------
Movie title: Big Hero 6
directors: Don Hall, Chris Williams
actors: Ryan Potter, Scott Adsit, Jamie Chung, T.J. Miller
----------------------
Movie title: Muppets Most Wanted
directors: James Bobin
actors: Ricky Gervais, Ty Burrell, Tina Fey, Steve Whitmire
----------------------
Movie title: Maleficent
directors: Robert Stromberg
actors: Angelina Jolie, Elle Fanning, Sharlto Copley, Lesley Manville
----------------------
Movie title: McFarland, USA
directors: Niki Caro
actors: Kevin Costner, Maria Bello, Ramiro Rodriguez, Carlos Pratts
----------------------
Movie title: Teen Beach 2
directors: Jeffrey Hornaday
actors: Ross Lynch, Maia Mitchell, Gracie Gillam, Garrett Clayton
----------------------
Movie title: Tinker Bell and the Legend of the NeverBeast
directors: Steve Loter
actors: Ginnifer Goodwin, Mae Whitman, Rosario Dawson, Lucy Liu
----------------------
Movie title: Bad Hair Day
directors: Erik Canuel
actors: Laura Marano, Leigh-Allyn Baker, Christian Campbell, Alain Goulem
----------------------
Movie title: Descendants
directors: Kenny Ortega
actors: Dove Cameron, Cameron Boyce, Booboo Stewart, Sofia Carson
----------------------
Movie title: Tomorrowland
directors: Brad Bird
actors: George Clooney, Britt Robertson, Hugh Laurie, Raffey Cassidy
----------------------
Movie title: Inside Out
directors: Pete Docter, Ronnie Del Carmen
actors: Amy Poehler, Bill Hader, Lewis Black, Mindy Kaling
----------------------
Movie title: Cinderella
directors: Kenneth Branagh
actors: Lily James, Cate Blanchett, Richard Madden, Helena Bonham Carter
----------------------
Movie title: The Good Dinosaur
directors: Peter Sohn
actors: Jeffrey Wright, Frances McDormand, Maleah Nipay-Padilla, Ryan Teeple
----------------------
Movie title: Moana
directors: Ron Clements, John Musker, Don Hall, Chris Williams
actors: Auli'i Cravalho, Dwayne Johnson, Rachel House, Temuera Morrison
----------------------
Movie title: The Jungle Book
directors: Jon Favreau
actors: Neel Sethi, Bill Murray, Ben Kingsley, Idris Elba
----------------------
Movie title: Alice Through the Looking Glass
directors: James Bobin
actors: Mia Wasikowska, Johnny Depp, Helena Bonham Carter, Anne Hathaway
----------------------
Movie title: Zootopia
directors: Byron Howard, Rich Moore, Jared Bush
actors: Ginnifer Goodwin, Jason Bateman, Idris Elba, Jenny Slate
----------------------
Movie title: Finding Dory
directors: Andrew Stanton, Angus MacLane
actors: Ellen DeGeneres, Albert Brooks, Ed O'Neill, Kaitlin Olson
----------------------
Movie title: Queen of Katwe
directors: Mira Nair
actors: Madina Nalwanga, David Oyelowo, Lupita Nyong'o, Martin Kabanza
----------------------
Movie title: Adventures in Babysitting
directors: John Schultz
actors: Sabrina Carpenter, Sofia Carson, Nikki Hahn, Mallory James Mahoney
----------------------
Movie title: Pete's Dragon
directors: David Lowery
actors: Bryce Dallas Howard, Robert Redford, Oakes Fegley, Oona Laurence
----------------------
Movie title: The Finest Hours
directors: Craig Gillespie
actors: Chris Pine, Casey Affleck, Ben Foster, Eric Bana
----------------------
Movie title: The Swap
directors: Jay Karas
actors: Peyton List, Jacob Bertrand, Claire Rankin, Darrin Rose
----------------------
Movie title: The BFG
directors: Steven Spielberg
actors: Mark Rylance, Ruby Barnhill, Penelope Wilton, Jemaine Clement
----------------------
Movie title: Cars 3
directors: Brian Fee
actors: Owen Wilson, Cristela Alonzo, Chris Cooper, Nathan Fillion
----------------------
Movie title: Coco
directors: Lee Unkrich, Adrian Molina
actors: Anthony Gonzalez, Gael García Bernal, Benjamin Bratt, Alanna Ubach
----------------------
Movie title: Pirates of the Caribbean: Dead Men Tell No Tales
directors: Joachim Rønning, Espen Sandberg
actors: Johnny Depp, Geoffrey Rush, Javier Bardem, Orlando Bloom
----------------------
Movie title: Descendants 2
directors: Kenny Ortega
actors: Dove Cameron, Cameron Boyce, Sofia Carson, Booboo Stewart
----------------------
Movie title: Beauty and the Beast
directors: Bill Condon
actors: Emma Watson, Dan Stevens, Luke Evans, Josh Gad
----------------------
Movie title: Toy Story 4
directors: Josh Cooley
actors: Tom Hanks, Tim Allen, Annie Potts, Tony Hale

In [9]:
browser.quit()

In [10]:
print(len(title_list), len(director_list), len(actor_list))

642 642 642

In [11]:
# make sure that directors belong to their corresponding movies
new_title_list=[]
new_director_list=[]

for i in range(len(director_list)):
    #count number of directors
    repet_times=len(director_list[i])
    
    for time in range(repet_times):
        new_title_list.append(title_list[i])
    
    for each in director_list[i]:
        new_director_list.append(each)

#### Director table

In [12]:
# create a dataframe
director_df = pd.DataFrame({"title": new_title_list,
                           "director": new_director_list})
director_df

                                                title          director
0                     Snow White and the Seven Dwarfs  William Cottrell
1                     Snow White and the Seven Dwarfs        David Hand
2                     Snow White and the Seven Dwarfs   Wilfred Jackson
3                     Snow White and the Seven Dwarfs       Larry Morey
4                     Snow White and the Seven Dwarfs      Perce Pearce
..                                                ...               ...
900  Pirates of the Caribbean: Dead Men Tell No Tales   Joachim Rønning
901  Pirates of the Caribbean: Dead Men Tell No Tales    Espen Sandberg
902                                     Descendants 2      Kenny Ortega
903                              Beauty and the Beast       Bill Condon
904                                       Toy Story 4       Josh Cooley

[905 rows x 2 columns]

In [13]:
#make sure actors belong to their corresponding movies
new_title_list_2=[]
new_actor_list=[]

for i in range(len(actor_list)):
    #count number of actors
    repet_times=len(actor_list[i])
    
    for time in range(repet_times):
        new_title_list_2.append(title_list[i])
    
    for each in actor_list[i]:
        new_actor_list.append(each)

In [14]:
print(len(new_title_list_2), len(new_actor_list))

2555 2555

#### Actor table

In [15]:
actor_df = pd.DataFrame({"title": new_title_list_2,
                        "cast": new_actor_list})
actor_df

                                title               cast
0     Snow White and the Seven Dwarfs  Adriana Caselotti
1     Snow White and the Seven Dwarfs    Harry Stockwell
2     Snow White and the Seven Dwarfs   Lucille La Verne
3     Snow White and the Seven Dwarfs         Roy Atwell
4                           Pinocchio       Dickie Jones
...                               ...                ...
2550             Beauty and the Beast           Josh Gad
2551                      Toy Story 4          Tom Hanks
2552                      Toy Story 4          Tim Allen
2553                      Toy Story 4        Annie Potts
2554                      Toy Story 4          Tony Hale

[2555 rows x 2 columns]

# Step two: Transform

### Table 1: box office table

In [17]:
disney_df['income_id'] = [i for i in range(1, len(disney_df) + 1)]
box_df = disney_df.copy()
box_df = box_df[['income_id', 'total_gross']]
box_df.columns = ['income_id', 'gross_income']
box_df.head()

   income_id  gross_income
0          1     184925485
1          2      84300000
2          3      83320000
3          4      65000000
4          5      85000000

### Table two: movie table

In [18]:
# movie table
movie_df = pd.merge(disney_df, 
                   rating_df,
                   left_on = 'movie_title',
                   right_on= 'Title')

new_movie_df = movie_df.copy()

# fill na
new_movie_df['genre'].fillna("No Genre", inplace = True)
new_movie_df['Duration'].fillna("No Duration", inplace = True)

#drop duplicates
new_movie_df.drop_duplicates(["movie_title"], keep='last', inplace=True)

new_movie_df['movie_id'] = [i for i in range(1, len(new_movie_df) + 1 )]
new_movie_df = new_movie_df[['movie_id', "income_id", 'Title', 'Duration', 'genre', 'release_date']]

#change the column names
new_movie_df.columns = ['movie_id', "income_id", 'movie_title', 'duration', 'genre', 'release_date']
new_movie_df

,movie_id,income_id,movie_title,duration,genre,release_date
1,1,1,Snow White and the Seven Dwarfs,83 min,Musical,1937-12-21
3,2,2,Pinocchio,88 min,Adventure,1940-02-09
5,3,3,Fantasia,125 min,Musical,1940-11-13
7,4,4,Song of the South,94 min,Adventure,1946-11-12
13,5,557,Cinderella,105 min,Drama,2015-03-13
...,...,...,...,...,...,...
189,111,571,Alice Through the Looking Glass,113 min,Adventure,2016-05-27
190,112,572,Finding Dory,97 min,Adventure,2016-06-17
191,113,573,The BFG,117 min,Adventure,2016-07-01
192,114,576,Queen of Katwe,124 min,Drama,2016-09-23
193,115,578,Moana,107 min,Adventure,2016-11-23

In [19]:
df_data = new_movie_df.merge(box_df, on='income_id', how='outer')
genre_sum = df_data.groupby(['genre']).sum()[['gross_income']].sort_values('gross_income', ascending=False)
genre_sum

                   gross_income
genre
Adventure            7683526518
Comedy               1897457815
Drama                 778349649
Musical               698964229
Western                97549742
Romantic Comedy        95149435
Thriller/Suspense      27569558
No Genre                 229128

### Table three: review table

In [20]:
disney_review_table = pd.merge(new_movie_df, 
                               rating_df,
                               left_on = 'movie_title',
                               right_on= 'Title')
disney_review_table.head()

,movie_id,income_id,movie_title,duration,genre,release_date,Title,Duration,IMDB_rating,Number_of_Reviews
0,1,1,Snow White and the Seven Dwarfs,83 min,Musical,1937-12-21,Snow White and the Seven Dwarfs,83 min,7.6,"173,805"
1,1,1,Snow White and the Seven Dwarfs,83 min,Musical,1937-12-21,Snow White and the Seven Dwarfs,83 min,7.6,"173,805"
2,2,2,Pinocchio,88 min,Adventure,1940-02-09,Pinocchio,88 min,7.4,"124,575"
3,2,2,Pinocchio,88 min,Adventure,1940-02-09,Pinocchio,88 min,7.4,"124,575"
4,3,3,Fantasia,125 min,Musical,1940-11-13,Fantasia,125 min,7.8,"85,242"

In [21]:
# review table
new_rating_df = disney_review_table.copy()

#dropna
new_rating_df = new_rating_df[new_rating_df['IMDB_rating'] != ""]

#remove_duplicates
new_rating_df.drop_duplicates(["movie_title"], keep='last', inplace=True)


#set index
new_rating_df['rating_id'] = [i for i in range(1, len(new_rating_df) + 1)]
new_rating_df = new_rating_df[['rating_id','IMDB_rating', 'Number_of_Reviews', 'movie_id']]
new_rating_df.columns = ['review_id','imdb_rating', 'number_of_reviews', 'movie_id']


# change datatype for reviews column
new_rating_df['number_of_reviews'] = new_rating_df['number_of_reviews'].str.replace(',', '')
new_rating_df['number_of_reviews'] = new_rating_df['number_of_reviews'].astype(int)


new_rating_df

     review_id imdb_rating  number_of_reviews  movie_id
1            1         7.6             173805         1
3            2         7.4             124575         2
5            3         7.8              85242         3
7            4         7.1              10684         4
10           5         6.9             152325         5
..         ...         ...                ...       ...
177        107         6.2              86811       111
178        108         7.3             228045       112
179        109         6.4              73711       113
180        110         7.4              14283       114
181        111         7.6             249860       115

[111 rows x 4 columns]

In [22]:
# top 10 higher store movies
highest_score_movie = disney_review_table[['Title','IMDB_rating']].sort_values("IMDB_rating", ascending=False)
highest_score_movie.head(10)

                  Title IMDB_rating
62            Toy Story         8.3
61            Toy Story         8.3
173          Inside Out         8.2
142        Finding Nemo         8.1
150     The Incredibles           8
131      Monsters, Inc.           8
176            Zootopia           8
110  The Straight Story           8
109  The Straight Story           8
112         Toy Story 2         7.9

In [23]:
# top 10 higher review movies
highest_reviews_movie = disney_review_table[['Title', 'Number_of_Reviews']].sort_values("Number_of_Reviews", ascending=False)
highest_reviews_movie.head(10)

                         Title Number_of_Reviews
128  Atlantis: The Lost Empire            98,604
127  Atlantis: The Lost Empire            98,604
17              101 Dalmatians            97,462
18              101 Dalmatians            97,462
174          The Good Dinosaur            97,043
138            Treasure Planet            96,776
143               Brother Bear            92,180
142               Finding Nemo           912,674
71                   First Kid             9,811
72                   First Kid             9,811

### Table four: Director table

In [24]:
temp_director_df = director_df.copy()

#split name
temp_director_df.loc[temp_director_df['director'].str.split().str.len() == 2, 'last name'] = temp_director_df['director'].str.split().str[-1]

#dropna
temp_director_df = temp_director_df[temp_director_df['last name'].notna()]

#remove duplicates
temp_director_df.drop_duplicates(["title", "director", 'last name'], keep='last', inplace=True)
temp_director_df.columns = ['title', 'first_name', 'last_name']

#add index
temp_director_df['director_id'] = [i for i in range(1, len(temp_director_df) + 1)]

# drop columns
new_director_df = temp_director_df.loc[:, ['first_name', 'last_name']]
new_director_df.columns = ['first_name', 'last_name']


#remove duplicates
new_director_df.drop_duplicates(['first_name', 'last_name'], keep='last', inplace=True)

#add index
new_director_df['director_id'] = [i for i in range(1, len(new_director_df) + 1)]
new_director_df = new_director_df[['director_id', 'first_name', 'last_name']]


new_director_df

     director_id        first_name last_name
184            1  William Cottrell  Cottrell
187            2       Larry Morey     Morey
188            3      Perce Pearce    Pearce
202            4       Jim Handley   Handley
203            5            T. Hee       Hee
..           ...               ...       ...
900          350   Joachim Rønning   Rønning
901          351    Espen Sandberg  Sandberg
902          352      Kenny Ortega    Ortega
903          353       Bill Condon    Condon
904          354       Josh Cooley    Cooley

[354 rows x 3 columns]

### Table five: Movie Directors table

In [25]:
#merge tables
director_df_join = pd.merge(temp_director_df, 
                            new_director_df,
                            on = ['first_name', 'last_name'])

disney_director_df = pd.merge(new_movie_df, 
                              director_df_join,
                              left_on = "movie_title",
                              right_on = 'title')

In [27]:
# build movie director table
movie_director_df = disney_director_df.copy()
movie_director_df = movie_director_df[['movie_id', 'director_id_y']]
movie_director_df.columns = ['movie_id', 'director_id']
movie_director_df

     movie_id  director_id
0           1            1
1           1           74
2           1           25
3           1            2
4           1            3
..        ...          ...
178       114          341
179       115          330
180       115          331
181       115          333
182       115          332

[183 rows x 2 columns]

In [46]:
#top 10 movies with most directors
director_grouped = disney_director_df.groupby(['title']).count()[['first_name']].sort_values(by=['first_name'], ascending=False)
director_grouped.columns = ['Number of Directors']
director_grouped.head(10)

                                 Number of Directors
title
Fantasia                                          11
Pinocchio                                          7
Snow White and the Seven Dwarfs                    6
The Jungle Book                                    5
Moana                                              4
Cinderella                                         4
Alice in Wonderland                                4
Sleeping Beauty                                    4
Beauty and the Beast                               3
Lady and the Tramp                                 3

In [45]:
# top 10 directors that direct most disney movies
director_count = disney_director_df.groupby(['first_name', 'last_name']).count()[['title']].sort_values(by="title", ascending=False)
director_count.columns = ['Number of Disney Movies']
director_count.head(10)

                                Number of Disney Movies
first_name          last_name
Wilfred Jackson     Jackson                           7
Hamilton Luske      Luske                             6
Clyde Geronimi      Geronimi                          5
Wolfgang Reitherman Reitherman                        4
Lee Unkrich         Unkrich                           3
Kirk Wise           Wise                              3
Kevin Lima          Lima                              3
John Musker         Musker                            3
John Lasseter       Lasseter                          3
Gary Trousdale      Trousdale                         3

### Table six: Actor table

In [30]:
temp_actor_df = actor_df.copy()

# split actor's name
temp_actor_df.loc[temp_actor_df['cast'].str.split().str.len() == 2, 'last name'] = temp_actor_df['cast'].str.split().str[-1]

# dropna
temp_actor_df = temp_actor_df[temp_actor_df['last name'].notna()]

# remove duplicates
temp_actor_df.drop_duplicates(["title", "cast", "last name"], keep='last', inplace=True)
# rename columns
temp_actor_df.columns = ['title', 'first_name', 'last_name']

# add index
temp_actor_df['actor_id'] = [i for i in range(1, len(temp_actor_df) + 1)]


# drop columns
new_actor_df = temp_actor_df.loc[:, ['first_name', 'last_name']]
new_actor_df.columns = ['first_name', 'last_name']

# remove duplicates
new_actor_df.drop_duplicates(['first_name', 'last_name'], keep='last', inplace=True)

# add index
new_actor_df['actor_id'] = [i for i in range(1, len(new_actor_df) + 1)]
new_actor_df = new_actor_df[['actor_id', 'first_name', 'last_name']]

new_actor_df

      actor_id         first_name  last_name
397          1  Adriana Caselotti  Caselotti
398          2    Harry Stockwell  Stockwell
400          3         Roy Atwell     Atwell
401          4       Dickie Jones      Jones
402          5      Christian Rub        Rub
...        ...                ...        ...
2550      1434           Josh Gad        Gad
2551      1435          Tom Hanks      Hanks
2552      1436          Tim Allen      Allen
2553      1437        Annie Potts      Potts
2554      1438          Tony Hale       Hale

[1438 rows x 3 columns]

### Table seven: Movie Actor table

In [31]:
#merge tables
actor_df_join = pd.merge(temp_actor_df, 
                        new_actor_df,
                        on=['first_name', 'last_name'])

disney_actor_df = pd.merge(new_movie_df, 
                           actor_df_join,
                           left_on = "movie_title",
                           right_on= 'title')

disney_actor_df.head()

,movie_id,income_id,movie_title,duration,genre,release_date,title,first_name,last_name,actor_id_x,actor_id_y
0,1,1,Snow White and the Seven Dwarfs,83 min,Musical,1937-12-21,Snow White and the Seven Dwarfs,Adriana Caselotti,Caselotti,1,1
1,1,1,Snow White and the Seven Dwarfs,83 min,Musical,1937-12-21,Snow White and the Seven Dwarfs,Harry Stockwell,Stockwell,2,2
2,1,1,Snow White and the Seven Dwarfs,83 min,Musical,1937-12-21,Snow White and the Seven Dwarfs,Roy Atwell,Atwell,3,3
3,2,2,Pinocchio,88 min,Adventure,1940-02-09,Pinocchio,Dickie Jones,Jones,4,4
4,2,2,Pinocchio,88 min,Adventure,1940-02-09,Pinocchio,Christian Rub,Rub,5,5

In [32]:
# build Movie Actor table
movie_actor_df = disney_actor_df.copy()
# select columns
movie_actor_df = movie_actor_df[['movie_id','actor_id_y']]
# rename columns
movie_actor_df.columns = ['movie_id', 'actor_id']
movie_actor_df

     movie_id  actor_id
0           1         1
1           1         2
2           1         3
3           2         4
4           2         5
..        ...       ...
450       114      1398
451       115      1379
452       115      1378
453       115      1380
454       115      1381

[455 rows x 2 columns]

In [43]:
#top 10 movies with most actors
movie_actors = disney_actor_df.groupby(['title']).count()[['first_name']].sort_values(by=['first_name'], ascending=False)
movie_actors.columns = ['Number of Actors on the list']
movie_actors.head(10)

                      Number of Actors on the list
title
The Jungle Book                                 11
The Parent Trap                                  8
The Shaggy Dog                                   8
Beauty and the Beast                             8
Freaky Friday                                    7
Cinderella                                       7
Alice in Wonderland                              7
101 Dalmatians                                   4
Tarzan                                           4
Song of the South                                4

In [41]:
# top 10 directors that direct most disney movies
actors_count = disney_actor_df.groupby(['first_name', 'last_name']).count()[['title']].sort_values(by="title", ascending=False)
actors_count.columns = ['Number of Disney Movies']
actors_count.head(10)

                          Number of Disney Movies
first_name     last_name
Tim Allen      Allen                            5
Anne Hathaway  Hathaway                         4
Jim Cummings   Cummings                         4
Joan Cusack    Cusack                           3
Lindsay Lohan  Lohan                            3
Corey Burton   Burton                           3
Fred MacMurray MacMurray                        3
John Goodman   Goodman                          3
Johnny Depp    Depp                             3
Glenn Close    Close                            3

# Step 3: Load
* Note: Once the database is ready, the ETL process can run. 
* SQL schema: https://github.com/wiseqx/ETL_Project/blob/master/sql/SQL_Schema.sql

In [35]:
# connect to database
# note: put your local path here
engine = create_engine('postgresql://postgres/disney_db')
connection = engine.connect()

In [36]:
# load all of data to PostgresSQL database
box_df.to_sql(name='boxoffice', con=engine, if_exists='append', index=False)
new_movie_df.to_sql(name='movies', con=engine, if_exists='append', index=False)
new_rating_df.to_sql(name='reviews', con=engine, if_exists='append', index=False)
new_director_df.to_sql(name='directors', con=engine, if_exists='append', index=False)
movie_director_df.to_sql(name='movie_directors', con=engine, if_exists='append', index=False)
new_actor_df.to_sql(name='voice_actors', con=engine, if_exists='append', index=False)
movie_actor_df.to_sql(name='movie_actors', con=engine, if_exists='append', index=False)

In [37]:
#Sample sql query test
query_str = open('sql/test.sql')
query_text = ""
for text in query_str:
    query_text = query_text + text
      
print(query_text)
print("-"*50)
df_query = pd.read_sql_query(query_text, con=engine)

df_query

CREATE VIEW top_rating_movie as
select m.movie_title, count(first_name) as "number_of_directors"
from directors d
		join movie_directors md on md.director_id = d.director_id
		join movies m on m.movie_id = md.movie_id
group by m.movie_title;

select t.movie_title, r.imdb_rating, t.number_of_directors, m.duration
from top_rating_movie t
join movies m on t.movie_title=m.movie_title
join reviews r on m.movie_id = r.movie_id;
--------------------------------------------------

,movie_title,imdb_rating,number_of_directors,duration
0,Snow White and the Seven Dwarfs,7.6,6,83 min
1,Pinocchio,7.4,7,88 min
2,Fantasia,7.8,11,125 min
3,Song of the South,7.1,2,94 min
4,Cinderella,6.9,4,105 min
...,...,...,...,...
101,Alice Through the Looking Glass,6.2,1,113 min
102,Finding Dory,7.3,2,97 min
103,The BFG,6.4,1,117 min
104,Queen of Katwe,7.4,1,124 min
105,Moana,7.6,4,107 min